"""GPU vs CPU granular sweep — the demo this whole CUDA plan was about.

For each N in --counts, generates a tiny .wbt with one GranularGroup of N
particles, runs it headless for --duration seconds, parses the periodic
kernel-ms readback log lines, reports the steady-state mean kernel ms/step
once particles have piled. Then prints a comparison table against the CPU
baseline from tests/granular-spike/results.md.

Usage:
    python tests/cuda/bench_granular_group.py
        # default sweep: N = 100, 200, 400, 600, 1000

    python tests/cuda/bench_granular_group.py --counts 100 250 500 1000 2000
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path
from statistics import mean

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[1]

# Parses: GranularGroup step 32: y min=… mean=… max=… (n=N, kernel X.XXX ms)
_KERNEL_RE = re.compile(
    r"GranularGroup step (?P<step>\d+): .*kernel (?P<ms>[0-9.]+) ms"
)
_SETTLE_STEP = 96  # skip the first ~1.5 s of sim (free-fall), measure pile-only

# CPU baseline from tests/granular-spike/results.md (2026-04-28). Numbers are
# average physics ms per simulated step at 32 ms basicTimeStep on the CPU
# Solid+Sphere path that motivated the CUDA plan.
_CPU_BASELINE_MS = {
    100: 0.545,
    200: 7.966,
    400: 180.327,
    600: float("inf"),  # didn't finish in 120 s wall budget
}


def _world_for(n: int) -> str:
    return f"""#VRML_SIM R2025a utf8
# Auto-generated by bench_granular_group.py for N={n}.

EXTERNPROTO "omnisim://projects/objects/backgrounds/protos/NightSky.proto"
EXTERNPROTO "omnisim://projects/objects/floors/protos/RectangleArena.proto"

WorldInfo {{
  basicTimeStep 16
  title "GranularGroup bench N={n}"
}}
Viewpoint {{
  orientation -0.3 -0.05 0.95 0.5
  position -1.5 -2.0 1.2
}}
NightSky {{
}}
DirectionalLight {{
  ambientIntensity 0.4
  direction 0.5 -1 -0.5
  intensity 1.5
  castShadows TRUE
}}
RectangleArena {{
  floorSize 0.6 0.6
  wallHeight 0.05
}}
GranularGroup {{
  radius 0.02
  count {n}
}}
"""


def _snapshot_webots_pids() -> set[int]:
    """Return the set of omnisim-bin/webots PIDs currently running.

    Used to scope `_kill_stale_webots()` so we only kill children *this* bench
    run spawned, not unrelated OmniSim sessions an agent or harness has open in
    parallel.
    """
    if os.name != "nt":
        return set()
    out = subprocess.run(
        ["tasklist", "/NH", "/FO", "CSV"],
        capture_output=True, text=True, errors="replace",
    )
    pids: set[int] = set()
    for line in (out.stdout or "").splitlines():
        if not line.lower().startswith('"webots'):
            continue
        parts = [p.strip('"') for p in line.split(",")]
        if len(parts) < 2:
            continue
        try:
            pids.add(int(parts[1]))
        except ValueError:
            continue
    return pids


def _kill_stale_webots(baseline_pids: set[int]) -> None:
    """Kill leftover omnisim-bin processes spawned by this run and wait until
    they are gone. Only PIDs *not* in `baseline_pids` are killed — anything
    that was already running when the bench started belongs to another session
    (parallel agent, open OmniSim window, harness) and must be left alone.

    Between iterations, the previous run's omnisim-bin may still be shutting
    down when the next one starts, which can race on the omnisim_log.txt
    file lock and cause the runner's `unlink()` to fail (exit 1, no kernel
    timings produced). This is the most common cause of mid-sweep failures.
    """
    if os.name != "nt":
        return
    import time
    survivors = _snapshot_webots_pids() - baseline_pids
    if not survivors:
        return
    pid_args: list[str] = []
    for pid in survivors:
        pid_args.extend(["/PID", str(pid)])
    subprocess.run(
        ["taskkill", "/F", *pid_args],
        capture_output=True,
    )
    # Poll for up to 5 seconds. Each tick costs ~50ms via tasklist.
    for _ in range(100):
        remaining = _snapshot_webots_pids() - baseline_pids
        if not remaining:
            return
        time.sleep(0.05)


def _run_one(n: int, duration: float, baseline_pids: set[int]) -> dict:
    world = HERE / f".bench_n{n}.wbt"
    world.write_text(_world_for(n), encoding="utf-8")

    log_path = REPO_ROOT / "omnisim_log.txt"
    headless_runner = REPO_ROOT / "scripts" / "dev" / "headless_runner.py"

    _kill_stale_webots(baseline_pids)

    env = os.environ.copy()
    env["OMNISIM_STRUCTURED_LOG"] = "1"
    env.setdefault("OMNISIM_HOME", str(REPO_ROOT))
    cmd = [sys.executable, str(headless_runner), str(world), "--duration", str(int(duration))]
    print(f"[bench] N={n}: launching headless ({duration} s) ...")
    run = subprocess.run(cmd, env=env, capture_output=True, text=True, encoding="utf-8", errors="replace")
    if run.returncode != 0:
        print("--- runner stdout ---")
        print(run.stdout)
        print("--- runner stderr ---")
        print(run.stderr, file=sys.stderr)
        return {"n": n, "ok": False, "error": f"runner exit {run.returncode}"}

    if not log_path.exists():
        return {"n": n, "ok": False, "error": "no log produced"}

    log_text = log_path.read_text(encoding="utf-8", errors="replace")
    samples: list[float] = []
    for m in _KERNEL_RE.finditer(log_text):
        step = int(m.group("step"))
        ms = float(m.group("ms"))
        if step >= _SETTLE_STEP:
            samples.append(ms)
    if not samples:
        return {"n": n, "ok": False, "error": "no kernel timings parsed"}

    return {
        "n": n,
        "ok": True,
        "samples": len(samples),
        "kernel_ms_mean": mean(samples),
        "kernel_ms_min": min(samples),
        "kernel_ms_max": max(samples),
    }


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--counts", type=int, nargs="+",
                   default=[100, 200, 400, 600, 1000])
    p.add_argument("--duration", type=int, default=4,
                   help="wall-clock seconds per N (default 4)")
    args = p.parse_args()

    # Snapshot pre-existing omnisim-bin PIDs so the per-iteration cleanup only
    # touches processes *this* bench spawned, not any OmniSim an agent or
    # harness has open in parallel.
    baseline_pids = _snapshot_webots_pids()

    results: list[dict] = []
    for n in args.counts:
        results.append(_run_one(n, args.duration, baseline_pids))

    # Cleanup
    for n in args.counts:
        artefact = HERE / f".bench_n{n}.wbt"
        artefact.unlink(missing_ok=True)

    # Report — ASCII-only so it survives Windows cp1252 console.
    print()
    print("| N | GPU kernel ms/step (mean) | min | max | samples | CPU ms/step (baseline) | speedup |")
    print("|---|---|---|---|---|---|---|")
    for r in results:
        n = r["n"]
        cpu = _CPU_BASELINE_MS.get(n)
        if cpu is None:
            cpu_str = "n/a"
        elif cpu == float("inf"):
            cpu_str = "DNF (>120 s)"
        else:
            cpu_str = f"{cpu:.3f}"
        if not r["ok"]:
            print(f"| {n} | FAIL: {r.get('error', '?')} | | | | {cpu_str} | |")
            continue
        if cpu and cpu != float("inf"):
            speedup = f"{cpu / r['kernel_ms_mean']:.1f}x"
        elif cpu == float("inf"):
            speedup = "inf (CPU DNF)"
        else:
            speedup = ""
        print(f"| {n} | {r['kernel_ms_mean']:.3f} | {r['kernel_ms_min']:.3f} | "
              f"{r['kernel_ms_max']:.3f} | {r['samples']} | {cpu_str} | {speedup} |")

    print()
    print("Notes:")
    print("- GPU column is the per-outer-step kernel cost (8 substeps x 2 launches = 16 launches).")
    print("- CPU baseline is from tests/granular-spike/results.md (2026-04-28). It measured the")
    print("  pre-CUDA Solid+Sphere physics path on this same machine.")
    print(f"- Settle window: kernel-ms samples taken from step >= {_SETTLE_STEP} "
          "(after the free-fall phase, when particles are piled and contacts are dense).")
    return 0 if all(r["ok"] for r in results) else 1


if __name__ == "__main__":
    sys.exit(main())
