# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate ``.proto.yaml`` schema sidecars from PROTO source files.

A sidecar is an agent-introspectable contract for a PROTO. The file
splits into two top-level sections:

* ``auto`` — regenerated from the PROTO on every run. Don't hand-edit;
  changes here will be clobbered.
* ``extra`` — hand-curated semantic metadata (units, ranges, semantic
  tags). Preserved across regeneration.

Run with ``python -m omnisim proto schema [paths...]``. With no paths it
walks every ``*.proto`` under ``projects/``. ``--check`` reports drift
without writing. ``--force`` overwrites even if the on-disk sidecar
looks hand-edited.
"""

from __future__ import annotations

import argparse
import io
import json
import sys
from pathlib import Path
from typing import Any

import yaml

from ..paths import REPO_ROOT
from .parser import ParsedProto, ProtoParseError, parse_proto_file


SIDECAR_SUFFIX = ".proto.yaml"
GENERATED_BANNER = (
    "# OmniSim PROTO schema sidecar.\n"
    "# `auto:` is regenerated by `python -m omnisim proto schema`; edits there are lost.\n"
    "# `extra:` is hand-curated and preserved across regeneration.\n"
)


# --------------------------------------------------------------------------- #
# Conversion: ParsedProto -> auto dict
# --------------------------------------------------------------------------- #


_FLOW_VECTOR_TYPES = frozenset({"SFVec2f", "SFVec3f", "SFColor", "SFRotation"})


class _FlowList(list):
    """List marker that the YAML dumper renders in inline flow style."""


def _maybe_flow(value: Any, vrml_type: str) -> Any:
    if isinstance(value, list) and vrml_type in _FLOW_VECTOR_TYPES:
        return _FlowList(value)
    return value


def _field_to_dict(f: Any) -> dict[str, Any]:
    out: dict[str, Any] = {
        "name": f.name,
        "type": f.type,
        "access": f.access,
        "default": _maybe_flow(f.default, f.type),
    }
    if f.hint:
        out["hint"] = f.hint
    if f.enum:
        out["enum"] = _FlowList(f.enum)
    if f.leading_comments:
        out["leading_comments"] = f.leading_comments
    return out


def _header_to_dict(p: ParsedProto) -> dict[str, Any]:
    h = p.header
    d: dict[str, Any] = {}
    if h.license:
        d["license"] = h.license
    if h.license_url:
        d["license_url"] = h.license_url
    if h.documentation_url:
        d["documentation_url"] = h.documentation_url
    if h.keywords:
        d["keywords"] = _FlowList(h.keywords)
    if h.template_language:
        d["template_language"] = h.template_language
    if h.description:
        d["description"] = h.description
    if h.tags:
        d["tags"] = _FlowList(h.tags)
    return d


def build_auto(p: ParsedProto, source_rel: str) -> dict[str, Any]:
    """Build the deterministic ``auto:`` section for one PROTO."""
    return {
        "proto": p.name,
        "source": source_rel,
        "header": _header_to_dict(p),
        "extern_protos": list(p.extern_protos),
        "fields": [_field_to_dict(f) for f in p.fields],
    }


# --------------------------------------------------------------------------- #
# YAML I/O — deterministic emit, preserve `extra:`
# --------------------------------------------------------------------------- #


class _BlockDumper(yaml.SafeDumper):
    """Forces block style for nested maps/lists so diffs stay readable."""


def _str_repr(dumper: yaml.SafeDumper, data: str) -> yaml.ScalarNode:
    style = "|" if "\n" in data else None
    return dumper.represent_scalar("tag:yaml.org,2002:str", data, style=style)


_BlockDumper.add_representer(str, _str_repr)


def _flow_list_repr(dumper: yaml.SafeDumper, data: _FlowList) -> yaml.SequenceNode:
    return dumper.represent_sequence("tag:yaml.org,2002:seq", list(data), flow_style=True)


_BlockDumper.add_representer(_FlowList, _flow_list_repr)


def dump_sidecar(auto: dict[str, Any], extra: dict[str, Any] | None) -> str:
    payload: dict[str, Any] = {"auto": auto}
    if extra:
        payload["extra"] = extra
    buf = io.StringIO()
    buf.write(GENERATED_BANNER)
    yaml.dump(payload, buf, Dumper=_BlockDumper, sort_keys=False,
              default_flow_style=False, allow_unicode=True, width=120)
    return buf.getvalue()


def load_sidecar(path: Path) -> dict[str, Any]:
    if not path.exists():
        return {}
    with path.open("r", encoding="utf-8") as fh:
        data = yaml.safe_load(fh) or {}
    if not isinstance(data, dict):
        return {}
    return data


# --------------------------------------------------------------------------- #
# Path resolution
# --------------------------------------------------------------------------- #


def _iter_protos(paths: list[str]) -> list[Path]:
    """Expand CLI paths into a flat list of .proto files."""
    if not paths:
        roots = [REPO_ROOT / "projects"]
    else:
        roots = [Path(p) if Path(p).is_absolute() else REPO_ROOT / p for p in paths]

    out: list[Path] = []
    for r in roots:
        if r.is_file() and r.suffix == ".proto":
            out.append(r)
        elif r.is_dir():
            out.extend(sorted(r.rglob("*.proto")))
        else:
            print(f"warning: skipping non-PROTO path: {r}", file=sys.stderr)
    return sorted(set(out))


# --------------------------------------------------------------------------- #
# Run
# --------------------------------------------------------------------------- #


def run(args: argparse.Namespace) -> int:
    protos = _iter_protos(args.paths)
    if not protos:
        print("no PROTOs found", file=sys.stderr)
        return 1

    written: list[Path] = []
    unchanged: list[Path] = []
    drifted: list[Path] = []
    errors: list[tuple[Path, str]] = []

    for proto_path in protos:
        sidecar = proto_path.with_suffix(".proto.yaml")
        try:
            parsed = parse_proto_file(proto_path)
        except ProtoParseError as e:
            errors.append((proto_path, str(e)))
            continue

        try:
            source_rel = str(proto_path.relative_to(REPO_ROOT)).replace("\\", "/")
        except ValueError:
            source_rel = str(proto_path)

        auto = build_auto(parsed, source_rel)
        existing = load_sidecar(sidecar)
        extra = existing.get("extra") if isinstance(existing.get("extra"), dict) else None
        rendered = dump_sidecar(auto, extra)

        on_disk = sidecar.read_text(encoding="utf-8") if sidecar.exists() else ""

        if rendered == on_disk:
            unchanged.append(sidecar)
            continue
        if args.check:
            drifted.append(sidecar)
            continue
        sidecar.write_text(rendered, encoding="utf-8")
        written.append(sidecar)

    summary = {
        "total": len(protos),
        "written": len(written),
        "unchanged": len(unchanged),
        "drifted": len(drifted),
        "errors": [{"path": str(p), "message": m} for p, m in errors],
    }

    if args.json:
        print(json.dumps(summary, indent=2))
    else:
        print(f"proto schema: {summary['total']} PROTOs scanned")
        print(f"  written:   {summary['written']}")
        print(f"  unchanged: {summary['unchanged']}")
        if drifted:
            print(f"  drifted:   {summary['drifted']} (run without --check to regenerate)")
            for d in drifted[:10]:
                print(f"    {d}")
            if len(drifted) > 10:
                print(f"    ... and {len(drifted) - 10} more")
        if errors:
            print(f"  errors:    {len(errors)}")
            for p, m in errors[:10]:
                print(f"    {p}: {m}")
            if len(errors) > 10:
                print(f"    ... and {len(errors) - 10} more")

    if args.check and drifted:
        return 2
    if errors:
        return 1
    return 0
