#!/bin/sh
# Toolchain probes for src/omnisim/Makefile, cached in one makefile fragment.
#
# Until 2026-09-02 the Makefile ran ~10 `$(shell ...)` probes at PARSE time on every
# invocation -- ccache (spawning the compiler), uname, nvcc + cygpath, `py -3` and
# `python` sys.prefix, ld.lld, and a three-process gcc-version expr -- ~1.1 s of the
# 1.6 s a no-op `make release` cost on the reference Windows machine, paid before the
# first dependency check of every incremental build. Their answers only change when
# the toolchain does, so this script answers them ONCE and re-answers only when its
# key changes: PATH, the compiler name, OSTYPE, this script, the Makefile, and the
# mtimes of every binary the probes resolve. One `sh` spawn per make instead of ten.
#
# usage: build_probes.sh <cache-dir> <CXX> <OSTYPE>   -- prints the fragment path.
# `make clean` deletes the cache; delete .build_tmp/make-probes.* to force a re-probe.
cache_dir="$1"; cxx="$2"; ostype="$3"
mk="$cache_dir/make-probes.mk"; keyfile="$cache_dir/make-probes.key"
[ -d "$cache_dir" ] || mkdir -p "$cache_dir" 2>/dev/null
here=${0%/*}
gcc_p=$(command -v gcc 2>/dev/null); ccache_p=$(command -v ccache 2>/dev/null)
nvcc_p=$(command -v nvcc 2>/dev/null); lld_p=$(command -v ld.lld 2>/dev/null)
python_p=$(command -v python 2>/dev/null); py_p=$(command -v py 2>/dev/null)
mtimes=$(stat -c %Y "$0" "$here/Makefile" $gcc_p $ccache_p $nvcc_p $lld_p $python_p $py_p 2>/dev/null | tr '\n' ',')
key="v1|$PATH|$cxx|$ostype|$gcc_p|$ccache_p|$nvcc_p|$lld_p|$python_p|$py_p|$mtimes"
if [ -f "$mk" ] && [ -f "$keyfile" ]; then
  read -r old_key < "$keyfile" || old_key=""
  if [ "$old_key" = "$key" ]; then echo "$mk"; exit 0; fi
fi
ccache=""
if [ -n "$ccache_p" ] && ccache "$cxx" --version >/dev/null 2>&1; then ccache="$ccache_p"; fi
hosttype=$(uname -m 2>/dev/null)
cuda_home=""
if [ -n "$nvcc_p" ]; then
  root=$(dirname "$(dirname "$nvcc_p")")
  if [ "$ostype" = "windows" ]; then cuda_home=$(cygpath -m -d "$root" 2>/dev/null); else cuda_home="$root"; fi
fi
gcc_ge_504=$(expr "$(gcc -dumpversion 2>/dev/null | sed -e 's/\.\([0-9][0-9]\)/\1/g' -e 's/\.\([0-9]\)/0\1/g' -e 's/^[0-9]\{3,4\}$/&00/')" \>= 50400 2>/dev/null)
py3_prefix=""; python_prefix=""
if [ "$ostype" = "windows" ]; then
  [ -n "$py_p" ] && py3_prefix=$(py -3 -c "import sys; print(sys.prefix)" 2>/dev/null)
  [ -n "$python_p" ] && python_prefix=$(python -c "import sys; print(sys.prefix)" 2>/dev/null)
fi
tmp="$mk.tmp.$$"
{
  echo "# generated by build_probes.sh -- do not edit; delete to re-probe"
  echo "OM_PROBES_CACHED := 1"
  echo "OM_PROBE_CCACHE := $ccache"
  echo "OM_PROBE_HOSTTYPE := $hosttype"
  echo "OM_PROBE_NVCC := $nvcc_p"
  echo "OM_PROBE_CUDA_HOME := $cuda_home"
  echo "OM_PROBE_LLD := $lld_p"
  echo "OM_PROBE_GCC_GE_504 := $gcc_ge_504"
  echo "OM_PROBE_PY3_PREFIX := $py3_prefix"
  echo "OM_PROBE_PYTHON_PREFIX := $python_prefix"
} > "$tmp" && mv -f "$tmp" "$mk" && printf '%s
' "$key" > "$keyfile"
echo "$mk"
