// Copyright 1996-2024 Cyberbotics Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Modifications copyright 2026 OmniLink, licensed under the Apache License, Version 2.0.

// Auto-generated by scripts/dev/make_omnisim_header_forwarders.py
// Deprecation shim for the canonical omnisim/ header. New code
// should prefer the omnisim/ path; the webots/ path is kept so
// legacy controllers (e.g. the Cyberbotics device tutorials)
// keep compiling unchanged.
#pragma once
#include "../omnisim/Proto.hpp"
