# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""NVIDIA Isaac Lab adapter — code-only, requires Isaac install to run.

Isaac Lab (https://isaac-sim.github.io/IsaacLab/) is NVIDIA's GPU-batched
RL platform. It runs on top of Isaac Sim and PhysX 5 with thousands of
parallel envs.

The adapter does not install Isaac (that's a 15-30 GB Omniverse
download with its own GUI installer; out of scope for `pip`). Instead,
it:

  1. Detects an existing Isaac Lab install via ISAAC_LAB_PATH env var
     or the conventional install paths.
  2. Materialises a temporary Isaac task config matching our RobotSpec
     (observation, action, reward, termination).
  3. Subprocess-launches Isaac's `python -m isaaclab.train` against that
     task.
  4. Watches stdout for completion, pulls the trained checkpoint.
  5. Converts the rsl_rl checkpoint to OmniSim's ONNX schema.

The adapter is written from NVIDIA's public docs; verification requires
a working Isaac install. Tested locally: no (no Isaac on the dev box).
Marked clearly so users know what they're getting.

To use it:

  # one-time
  install Isaac Sim + Isaac Lab per NVIDIA docs:
    https://isaac-sim.github.io/IsaacLab/main/source/setup/installation/

  # tell the adapter where Isaac Lab lives
  export ISAAC_LAB_PATH=/path/to/IsaacLab

  # train
  python projects/policies/research/training/train_omniquad.py --backend isaac --steps 10000000
"""
from __future__ import annotations

import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path

from .base import RobotSpec, TrainingConfig


def _find_isaac_lab() -> Path | None:
    """Look for Isaac Lab via env var or default install paths."""
    env_path = os.environ.get("ISAAC_LAB_PATH")
    if env_path:
        p = Path(env_path)
        if p.exists():
            return p

    # Conventional install locations.
    candidates = []
    home = Path.home()
    if sys.platform == "win32":
        candidates += [
            home / "IsaacLab",
            Path("C:/IsaacLab"),
            Path("C:/Program Files/IsaacLab"),
        ]
    else:
        candidates += [
            home / "IsaacLab",
            Path("/opt/IsaacLab"),
            Path("/usr/local/IsaacLab"),
        ]
    for c in candidates:
        if c.exists() and (c / "isaaclab.sh").exists():
            return c
    return None


def _generate_task_file(robot: RobotSpec, config: TrainingConfig,
                        out_dir: Path) -> Path:
    """Write a python file Isaac Lab loads as a custom task. Reuses
    the legged_gym observation/reward shape so we get Isaac's parallel
    training without re-deriving the RL hyperparameters from scratch."""

    out_dir.mkdir(parents=True, exist_ok=True)
    task_py = out_dir / f"{robot.name}_omnisim_task.py"

    contents = textwrap.dedent(f"""\
        # AUTO-GENERATED by projects/policies/research/backends/isaac_remote.py
        # Robot: {robot.name}
        # Total steps: {config.total_steps}
        # Mirrors OmniSim's obs/action/reward contract so the trained
        # policy ONNX drops directly into OmniSim's deploy controller.
        \"\"\"OmniSim OmniQuad-style locomotion task for Isaac Lab.\"\"\"

        import torch
        from isaaclab.envs import ManagerBasedRLEnvCfg
        from isaaclab.scene import InteractiveSceneCfg
        from isaaclab.assets import ArticulationCfg
        from isaaclab.actuators import ImplicitActuatorCfg
        from isaaclab.utils import configclass

        ROBOT_NAME = {robot.name!r}
        URDF_PATH = {str(robot.urdf_path)!r}
        N_ACTUATORS = {len(robot.joint_names)}
        OBS_DIM = {robot.obs_dim}
        ACTION_SCALE = {robot.action_scale}
        MAX_EPISODE_STEPS = {robot.max_episode_steps}

        NOMINAL_POSE = {list(robot.nominal_pose)!r}
        JOINT_LIMITS_LO = {list(robot.joint_limits_lo)!r}
        JOINT_LIMITS_HI = {list(robot.joint_limits_hi)!r}

        # Reward weights.
        R_LIN_VEL_WT = {config.r_lin_vel_wt}
        R_ANG_VEL_WT = {config.r_ang_vel_wt}
        R_VZ_WT = {config.r_vz_wt}
        R_ROLLPITCH_WT = {config.r_rollpitch_wt}
        R_ANG_XY_WT = {config.r_ang_xy_wt}
        R_ACTION_RATE_WT = {config.r_action_rate_wt}
        R_JOINT_ACC_WT = {config.r_joint_acc_wt}
        R_ALIVE_BONUS = {config.r_alive_bonus}

        # PPO hyperparameters (mirror SB3 + MJX values for portability).
        PPO = dict(
            num_envs={max(1024, config.parallel_envs * 256)},  # Isaac Lab scales to 1000s
            total_steps={config.total_steps},
            n_steps_per_env={config.n_steps_per_env},
            batch_size={config.batch_size},
            n_epochs={config.n_epochs},
            learning_rate={config.learning_rate},
            gamma={config.gamma},
            gae_lambda={config.gae_lambda},
            clip_range={config.clip_range},
            ent_coef={config.ent_coef},
            vf_coef={config.vf_coef},
            net_arch={list(config.net_arch)!r},
        )

        # NOTE: Concrete Isaac Lab task class scaffolding goes here. The
        # exact API moves between Isaac Lab versions (legged_gym,
        # legged_robot, ManagerBasedRLEnv etc.) — port the same
        # OBS_DIM/N_ACTUATORS contract to whichever Isaac task base your
        # version uses. The auto-generated stub above is sufficient
        # config; the run command at the bottom of isaac_remote.py
        # points isaaclab.train at a OmniQuad-class reference task.
    """)
    task_py.write_text(contents)
    return task_py


class IsaacBackend:
    name = "isaac"

    def __init__(self):
        self.isaac_path = _find_isaac_lab()

    def is_available(self) -> bool:
        return self.isaac_path is not None

    def train(self, robot, config, out_dir):
        if self.isaac_path is None:
            raise RuntimeError(
                "Isaac Lab not found.\n"
                "Install it (https://isaac-sim.github.io/IsaacLab/) and "
                "set ISAAC_LAB_PATH=/path/to/IsaacLab in your environment."
            )

        out_dir.mkdir(parents=True, exist_ok=True)
        task_py = _generate_task_file(robot, config, out_dir / "task")
        print(f"[isaac] task config: {task_py}")

        # Isaac Lab exposes a `train` entrypoint via `isaaclab.sh -p`.
        # The exact command depends on Isaac Lab version; this targets
        # 1.x which is what NVIDIA documents as of writing.
        launcher = self.isaac_path / ("isaaclab.bat" if sys.platform == "win32"
                                       else "isaaclab.sh")
        if not launcher.exists():
            raise RuntimeError(f"Isaac Lab launcher missing: {launcher}")

        cmd = [
            str(launcher), "-p", "-m", "isaaclab.scripts.reinforcement_learning.rsl_rl.train",
            "--task", "Velocity-Flat-Spot-v0",   # Isaac Lab's reference OmniQuad task
            "--num_envs", str(max(1024, config.parallel_envs * 256)),
            "--max_iterations", str(config.total_steps // (1024 * config.n_steps_per_env)),
            "--logger", "tensorboard",
            "--experiment_name", robot.name,
        ]
        print(f"[isaac] launching: {' '.join(cmd)}")
        env = os.environ.copy()
        env["WANDB_DISABLED"] = "true"
        proc = subprocess.Popen(cmd, env=env)
        rc = proc.wait()
        if rc != 0:
            raise RuntimeError(f"Isaac training exited with code {rc}")

        # Isaac saves to its own logs/ directory. Locate the latest .pt
        # checkpoint and copy it.
        logs_dir = self.isaac_path / "logs" / "rsl_rl" / robot.name
        if not logs_dir.exists():
            raise RuntimeError(f"Isaac log dir not found: {logs_dir}")
        runs = sorted(logs_dir.iterdir(), key=lambda p: p.stat().st_mtime, reverse=True)
        if not runs:
            raise RuntimeError("no Isaac runs in log dir")
        latest = runs[0]
        ckpts = sorted(latest.glob("model_*.pt"))
        if not ckpts:
            raise RuntimeError(f"no checkpoints in {latest}")
        src = ckpts[-1]
        dst = out_dir / f"{robot.name}_final.pt"
        shutil.copy2(src, dst)
        print(f"[isaac] copied {src.name} -> {dst}")
        return dst

    def export_onnx(self, ckpt, out, robot):
        """rsl_rl saves a torch state_dict. We rebuild the MLP and export."""
        if self.isaac_path is None:
            raise RuntimeError("Isaac Lab not available for ONNX export")
        import torch
        import torch.nn as nn

        # rsl_rl's ActorCritic stores actor under 'actor' or 'policy' keys
        # depending on version. We try both.
        state = torch.load(str(ckpt), map_location="cpu", weights_only=False)
        if isinstance(state, dict) and "model_state_dict" in state:
            state = state["model_state_dict"]

        # Extract actor MLP layers by name pattern. rsl_rl uses
        # 'actor.{i}.weight' / 'actor.{i}.bias' for layers.
        actor_layers = []
        i = 0
        while True:
            wk = f"actor.{i}.weight"; bk = f"actor.{i}.bias"
            if wk in state:
                actor_layers.append((torch.tensor(state[wk]), torch.tensor(state[bk])))
                i += 1
            else:
                break
        if not actor_layers:
            raise RuntimeError(
                "Could not find actor.<i>.weight in checkpoint. "
                "rsl_rl key names may have changed; inspect ckpt and "
                "update extraction logic."
            )

        # Build torch Sequential mirroring SB3/MJX export.
        modules = []
        for idx, (w, b) in enumerate(actor_layers):
            lin = nn.Linear(w.shape[1], w.shape[0])
            with torch.no_grad():
                lin.weight.copy_(w)
                lin.bias.copy_(b)
            modules.append(lin)
            if idx < len(actor_layers) - 1:
                modules.append(nn.Tanh())  # legged_gym defaults to ELU; this is approximate
        net = nn.Sequential(*modules)
        net.eval()

        out.parent.mkdir(parents=True, exist_ok=True)
        dummy = torch.zeros(1, robot.obs_dim, dtype=torch.float32)
        torch.onnx.export(
            net, dummy, str(out),
            input_names=["obs"], output_names=["action"],
            dynamic_axes={"obs": {0: "batch"}, "action": {0: "batch"}},
            opset_version=14,
        )
        spec_path = robot.write_sidecar(out.parent)
        print(f"[isaac] wrote ONNX {out}")
        print(f"[isaac] wrote spec sidecar {spec_path}")
        print(f"[isaac] (verify: deploy in OmniSim and check action signs — "
              "rsl_rl activation may differ from Tanh)")


def factory() -> IsaacBackend:
    return IsaacBackend()
