# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""city_traffic — supervisor that drives ambient traffic on an NxN street grid.

Moves a fleet of DEF'd Car nodes (CAR0..CARn) kinematically. The cars are static
Car.proto decoration, so the supervisor owns their pose each step — deterministic,
no physics to fight. The grid is read from the generated city_grid.json so the
world and this controller can never drift (see scripts/dev/gen_city_traffic.py).

Cars drive the network and ROUTE through it: at each junction a car goes straight
or turns right (chosen randomly), and U-turns on a smooth arc at the road ends.

Gridlock-free by construction:
  * synchronized 2-phase signal (NS-green / all-red / EW-green / all-red) — a car
    only enters a junction when its road's axis is green, so NS and EW flows never
    occupy a junction at once;
  * straight + RIGHT turns only (no left turn across oncoming) — the same-phase
    movements never cross;
  * "don't block the box": a car only turns if the exit lane is clear, so it can
    always fully clear the junction;
  * front-of-lane car-following keeps gaps and queues cars at red lights.
"""

from __future__ import annotations

import json
import math
import os
import random
import time

from omnisim import Supervisor

random.seed(11)

CARLEN = 4.4
GAP = 3.0       # min bumper gap
T_GREEN = 8.0
T_AMBER = 2.0
P_TURN = 0.32   # chance a car turns right (vs straight) at a junction
WALK = 1.35     # pedestrian walk speed (m/s)
PED_GAP = 1.6   # min arc gap between pedestrians on a loop
STEP_K = 4.2    # leg-swing cycles per metre walked (stride ~ 1.5 m)
LEG_AMP = 0.55  # leg swing amplitude (rad)
ARM_AMP = 0.45  # arm swing amplitude (rad)
BROWSE_PROB = 0.0032  # per-step chance a walking ped stops to browse a shopfront (32 ms steps)
CROSS_SPEED = 1.9     # m/s, brisk walk across a road at a zebra crossing
CYCLE_S = 130.0       # seconds for a full day -> night -> day cycle
START_TOD = 0.60      # start near dusk so night shows up quickly
BIG = 1e9

# Grid spec generated by scripts/dev/gen_city_traffic.py — world + controller share it.
with open(os.path.join(os.path.dirname(os.path.abspath(__file__)), "city_grid.json")) as _fh:
    _SPEC = json.load(_fh)
XS, YS = _SPEC["xs"], _SPEC["ys"]
STUB, LANE, H, CRUISE = _SPEC["stub"], _SPEC["lane"], _SPEC["H"], _SPEC["cruise"]

# road id -> axis, fixed (perpendicular) coord, travel range, junction coords.
ROADS = {}
for _j, _y in enumerate(YS):
    ROADS["EW%d" % _j] = {"axis": "EW", "fixed": _y, "lo": XS[0] - STUB, "hi": XS[-1] + STUB, "inter": list(XS)}
for _i, _x in enumerate(XS):
    ROADS["NS%d" % _i] = {"axis": "NS", "fixed": _x, "lo": YS[0] - STUB, "hi": YS[-1] + STUB, "inter": list(YS)}

INIT = [(c["road"], c["dir"], c["u"]) for c in _SPEC["cars"]]


def rightv(d):
    return (d[1], -d[0])


def car_pose(road, dr, u):
    R = ROADS[road]
    if R["axis"] == "EW":
        lat = R["fixed"] - LANE if dr > 0 else R["fixed"] + LANE
        return (u, lat), ((1.0, 0.0) if dr > 0 else (-1.0, 0.0))
    lat = R["fixed"] + LANE if dr > 0 else R["fixed"] - LANE
    return (lat, u), ((0.0, 1.0) if dr > 0 else (0.0, -1.0))


def nearest_index(arr, v):
    return min(range(len(arr)), key=lambda i: abs(arr[i] - v))


def lerp(a, b, t):
    return a + (b - a) * t


def day_factor(tod):
    """1.0 = full day, 0.0 = full night, with dawn/dusk ramps. tod in [0,1)."""
    if tod < 0.05:
        return 0.0
    if tod < 0.15:
        return (tod - 0.05) / 0.10
    if tod < 0.55:
        return 1.0
    if tod < 0.65:
        return 1.0 - (tod - 0.55) / 0.10
    return 0.0


def main() -> None:
    sup = Supervisor()
    dt_ms = int(sup.getBasicTimeStep())
    dt = dt_ms / 1000.0

    stats_path = os.environ.get("CITY_TRAFFIC_STATS")
    stats_fh = open(stats_path, "w") if stats_path else None
    if stats_fh:
        stats_fh.write("t,phase,cars,min_gap,mean_speed,turning,wall\n"); stats_fh.flush()
    wall0 = time.time()

    # Perf probe: CITY_TRAFFIC_IDLE=1 steps the world with the supervisor doing
    # NOTHING (no logic, no scene writes). Comparing its speed factor against a
    # normal run splits "engine + step handshake" cost from "controller" cost.
    if os.environ.get("CITY_TRAFFIC_IDLE"):
        n = 0
        while sup.step(dt_ms) != -1:
            n += 1
            if stats_fh and n % max(1, int(1.0 / dt)) == 0:
                stats_fh.write("%.1f,IDLE,0,0,0,0,%.2f\n" % (n * dt, time.time() - wall0)); stats_fh.flush()
        return

    sig_ns = sup.getFromDef("SIG_NS_APP")
    sig_ew = sup.getFromDef("SIG_EW_APP")
    ns_f = sig_ns.getField("emissiveColor") if sig_ns else None
    ew_f = sig_ew.getField("emissiveColor") if sig_ew else None
    GREEN, RED, AMBER = [0.0, 0.85, 0.12], [0.9, 0.05, 0.05], [0.85, 0.45, 0.0]

    # --- day/night control handles (sun_marker only drives sun DIRECTION, so
    #     intensity/colour/sky-luminosity/emissives are ours to set) ---
    def _fld(defname, field):
        n = sup.getFromDef(defname)
        return n.getField(field) if n else None
    sun_int_f = _fld("SUN", "intensity")
    fill_int_f = _fld("NIGHTFILL", "intensity")
    sky_lum_f = _fld("SKY", "luminosity")
    win_f = _fld("MAT_win", "emissiveColor")
    shop_f = _fld("MAT_shop", "emissiveColor")
    sgs_f = _fld("MAT_sign_s", "emissiveColor")
    sgr_f = _fld("MAT_sign_r", "emissiveColor")
    last_lum = [1.15]; last_sun = [4.3]

    cars = []
    for i, (road, dr, u) in enumerate(INIT):
        node = sup.getFromDef("CAR%d" % i)
        if node is None:
            continue
        pos, hd = car_pose(road, dr, u)
        cars.append({"tf": node.getField("translation"), "rf": node.getField("rotation"),
                     "road": road, "dir": dr, "u": u, "pos": pos, "hd": hd,
                     "mode": "straight", "moved": 0.0, "dj": None,
                     "ctr": (0, 0), "rad": 1.0, "e": (0, 0), "f": (0, 0),
                     "th": 0.0, "thmax": 0.0, "after": None, "key": None})

    def _rot(defname):
        n = sup.getFromDef(defname)
        return n.getField("rotation") if n else None

    peds = []
    for i, p in enumerate(_SPEC.get("peds", [])):
        node = sup.getFromDef("PED%d" % i)
        if node is None:
            continue
        lx0, ly0, lx1, ly1 = p["loop"]
        Lx, Ly = lx1 - lx0, ly1 - ly0
        peds.append({"tf": node.getField("translation"), "rf": node.getField("rotation"),
                     "lf": _rot("PED%d_LEGF" % i), "lb": _rot("PED%d_LEGB" % i),
                     "al": _rot("PED%d_ARML" % i), "ar": _rot("PED%d_ARMR" % i),
                     "loop": tuple(p["loop"]), "Lx": Lx, "Ly": Ly, "P": 2 * (Lx + Ly),
                     "s": p["s"], "dist": p["s"], "amp": 0.0,
                     "bt": 0.0, "bdur": 0.0, "hv": (1.0, 0.0), "x": 0.0, "y": 0.0})

    bnode = sup.getFromDef("BUS")
    bspec = _SPEC.get("bus")
    bus = None
    if bnode and bspec:
        bus = {"tf": bnode.getField("translation"), "rf": bnode.getField("rotation"),
               "wp": bspec["wp"], "speed": bspec.get("speed", 6.0), "i": 1,
               "px": bspec["wp"][0][0], "py": bspec["wp"][0][1], "hv": (1.0, 0.0), "dwell": 0.0}

    crossers = []
    for cr in _SPEC.get("crossers", []):
        node = sup.getFromDef("PED%d" % cr["i"])
        if node is None:
            continue
        crossers.append({"tf": node.getField("translation"), "rf": node.getField("rotation"),
                         "lf": _rot("PED%d_LEGF" % cr["i"]), "lb": _rot("PED%d_LEGB" % cr["i"]),
                         "al": _rot("PED%d_ARML" % cr["i"]), "ar": _rot("PED%d_ARMR" % cr["i"]),
                         "A": tuple(cr["a"]), "B": tuple(cr["b"]),
                         "start_green": "NS" if cr["axis"] == "EW" else "EW",
                         "at": 0, "moving": False, "px": cr["a"][0], "py": cr["a"][1],
                         "dist": 0.0, "amp": 0.0})

    dnode = sup.getFromDef("DOG")
    dspec = _SPEC.get("dog")
    dog = None
    if dnode and dspec and 0 <= dspec.get("ped", -1) < len(peds):
        dog = {"tf": dnode.getField("translation"), "rf": dnode.getField("rotation"),
               "ped": dspec["ped"], "hv": (1.0, 0.0)}

    uturn_busy = {}

    def try_right_turn(c, jc, snap):
        """Switch c into a right-turn arc onto the perpendicular road, if the exit
        is clear (don't block the box). Returns True if the turn started."""
        R = ROADS[c["road"]]; dr = c["dir"]
        if R["axis"] == "EW":
            J = (jc, R["fixed"]); hd = (float(dr), 0.0)
            new_axis, ridx = "NS", nearest_index(XS, jc)
        else:
            J = (R["fixed"], jc); hd = (0.0, float(dr))
            new_axis, ridx = "EW", nearest_index(YS, jc)
        hdp = (hd[1], -hd[0])
        p_out = (J[0] + hdp[0] * H - hd[0] * LANE, J[1] + hdp[1] * H - hd[1] * LANE)
        # don't block the box: refuse the turn only if a car sits ON the exit lane
        # near p_out (lane-aware — a car in the opposite lane must NOT veto the turn).
        perp = (-hdp[1], hdp[0])
        for q in snap:
            rel = (q[0] - p_out[0], q[1] - p_out[1])
            lon = rel[0] * hdp[0] + rel[1] * hdp[1]
            lat = abs(rel[0] * perp[0] + rel[1] * perp[1])
            if lat < 2.0 and -CARLEN < lon < CARLEN + GAP + 2.0:
                return False
        p_in = (J[0] - hd[0] * H + hdp[0] * LANE, J[1] - hd[1] * H + hdp[1] * LANE)
        c["mode"] = "arc"
        c["ctr"] = (J[0] + (hdp[0] - hd[0]) * H, J[1] + (hdp[1] - hd[1]) * H)
        c["rad"] = H - LANE
        c["e"] = (-hdp[0], -hdp[1]); c["f"] = hd
        c["th"] = 0.0; c["thmax"] = math.pi / 2
        new_dir = (1 if hdp[1] > 0 else -1) if new_axis == "NS" else (1 if hdp[0] > 0 else -1)
        new_u = p_out[1] if new_axis == "NS" else p_out[0]
        c["after"] = ("%s%d" % (new_axis, ridx), new_dir, new_u)
        c["key"] = None
        c["pos"] = p_in; c["hd"] = hd
        return True

    phase, phase_t, step_n = 0, 0.0, 0
    last_phase_written = -1   # force the first signal write
    last_nf = -9.0            # force the first day/night write
    while sup.step(dt_ms) != -1:
        phase_t += dt
        if phase_t >= (T_GREEN if phase in (0, 2) else T_AMBER):
            phase_t = 0.0; phase = (phase + 1) % 4
        green_axis = {0: "NS", 1: None, 2: "EW", 3: None}[phase]
        if ns_f and phase != last_phase_written:
            last_phase_written = phase
            ns_f.setSFColor(GREEN if green_axis == "NS" else (AMBER if phase == 1 else RED))
            ew_f.setSFColor(GREEN if green_axis == "EW" else (AMBER if phase == 3 else RED))

        # --- day/night cycle: dim sun + sky, raise night fill, light up windows/signs.
        #     Every setSF* is a scene write; only push when the factor moved >1%
        #     (zero writes through the long day/night plateaus). ---
        tod = (START_TOD + (step_n * dt) / CYCLE_S) % 1.0
        df = day_factor(tod); nf = 1.0 - df
        if abs(nf - last_nf) > 0.01:
            last_nf = nf
            if fill_int_f:
                fill_int_f.setSFFloat(nf * 0.35)
            if win_f:
                win_f.setSFColor([lerp(0.02, 0.55, nf), lerp(0.03, 0.45, nf), lerp(0.04, 0.20, nf)])
            if shop_f:
                shop_f.setSFColor([lerp(0.22, 0.80, nf), lerp(0.27, 0.62, nf), lerp(0.30, 0.32, nf)])
            if sgs_f:
                sgs_f.setSFColor([lerp(0.40, 0.95, nf), lerp(0.32, 0.80, nf), lerp(0.06, 0.20, nf)])
            if sgr_f:
                sgr_f.setSFColor([lerp(0.34, 0.95, nf), lerp(0.04, 0.18, nf), lerp(0.04, 0.18, nf)])
            # sun intensity + sky luminosity drive an IBL/sky rebake, so only nudge
            # them when they change appreciably (keeps it cheap).
            tgt_sun = 0.08 + df * 4.2
            if sun_int_f and abs(tgt_sun - last_sun[0]) > 0.12:
                sun_int_f.setSFFloat(tgt_sun); last_sun[0] = tgt_sun
            tgt_lum = 0.10 + df * 1.05
            if sky_lum_f and abs(tgt_lum - last_lum[0]) > 0.07:
                try:
                    sky_lum_f.setSFFloat(tgt_lum); last_lum[0] = tgt_lum
                except Exception:
                    pass

        snap = [c["pos"] for c in cars]

        for c in cars:
            c["moved"] = 0.0
            if c["mode"] == "arc":
                c["th"] += (CRUISE * dt) / c["rad"]
                c["moved"] = CRUISE * dt
                if c["th"] >= c["thmax"]:
                    if c["key"]:
                        uturn_busy.pop(c["key"], None)
                    c["road"], c["dir"], c["u"] = c["after"]
                    c["mode"] = "straight"; c["dj"] = None; c["key"] = None
                    c["pos"], c["hd"] = car_pose(c["road"], c["dir"], c["u"])
                else:
                    th, e, f, ct, rad = c["th"], c["e"], c["f"], c["ctr"], c["rad"]
                    ca, sa = math.cos(th), math.sin(th)
                    c["pos"] = (ct[0] + rad * (ca * e[0] + sa * f[0]),
                                ct[1] + rad * (ca * e[1] + sa * f[1]))
                    hx, hy = -sa * e[0] + ca * f[0], -sa * e[1] + ca * f[1]
                    m = math.hypot(hx, hy) or 1.0
                    c["hd"] = (hx / m, hy / m)
            else:  # straight
                R = ROADS[c["road"]]; dr = c["dir"]; u = c["u"]
                dist_stub = (R["hi"] - u) if dr > 0 else (u - R["lo"])
                nextj, bestd = None, BIG
                for ci in R["inter"]:
                    d = dr * (ci - u)
                    if 0.05 < d < bestd:
                        bestd, nextj = d, ci
                green = (green_axis == R["axis"])
                dist_stop = BIG
                if not green:
                    for ci in R["inter"]:
                        d = dr * ((ci - dr * H) - u)
                        if d > -1.0:
                            dist_stop = min(dist_stop, max(0.0, d))
                # decision at the stop line when green
                if green and nextj is not None and c["dj"] != nextj:
                    if dr * (u - (nextj - dr * H)) >= -2.0:
                        c["dj"] = nextj
                        if random.random() < P_TURN:
                            try_right_turn(c, nextj, snap)
                if c["mode"] != "arc":
                    dist_follow = BIG
                    for o in cars:
                        if o is c or o["mode"] != "straight" or o["road"] != c["road"] or o["dir"] != dr:
                            continue
                        d = dr * (o["u"] - u)
                        if d > 0:
                            dist_follow = min(dist_follow, max(0.0, d - (CARLEN + GAP)))
                    adv = max(0.0, min(CRUISE * dt, dist_stub, dist_stop, dist_follow))
                    c["u"] += dr * adv; c["moved"] = adv
                    c["pos"], c["hd"] = car_pose(c["road"], dr, c["u"])
                    if dist_stub - adv < 0.05:
                        key = (c["road"], "hi" if dr > 0 else "lo")
                        if uturn_busy.get(key) in (None, c):
                            uturn_busy[key] = c
                            right = rightv(c["hd"])
                            c["mode"] = "arc"
                            c["ctr"] = (c["pos"][0] - right[0] * LANE, c["pos"][1] - right[1] * LANE)
                            c["rad"] = LANE; c["e"] = right; c["f"] = c["hd"]
                            c["th"] = 0.0; c["thmax"] = math.pi
                            c["after"] = (c["road"], -c["dir"], R["hi"] if dr > 0 else R["lo"])
                            c["key"] = key

            # a car queued at a light hasn't moved: skip the (expensive) scene writes
            if c["moved"] > 0.0:
                p, h = c["pos"], c["hd"]
                c["tf"].setSFVec3f([p[0], p[1], 0.0])
                c["rf"].setSFRotation([0.0, 0.0, 1.0, math.atan2(h[1], h[0])])

        # ---- pedestrians: walk the loop, pause to browse shopfronts, swing limbs ----
        for pi, pd in enumerate(peds):
            P = pd["P"]
            if pd["bt"] > 0.0:                          # window-shopping: paused, facing the shop
                pd["bt"] += dt
                if pd["bt"] >= pd["bdur"]:
                    pd["bt"] = 0.0
                adv = 0.0
            else:
                gap = P
                for o in peds:
                    if o is pd or o["loop"] != pd["loop"]:
                        continue
                    d = (o["s"] - pd["s"]) % P
                    if 0 < d < gap:
                        gap = d
                adv = min(WALK * dt, max(0.0, gap - PED_GAP))
                pd["s"] = (pd["s"] + adv) % P
                pd["dist"] += adv
                if adv > 0.004 and random.random() < BROWSE_PROB:
                    pd["bt"] = 1e-6; pd["bdur"] = 2.5 + random.random() * 3.5
            s = pd["s"]; lx0, ly0, lx1, ly1 = pd["loop"]; Lx, Ly = pd["Lx"], pd["Ly"]
            if s < Lx:
                px, py, hx, hy = lx0 + s, ly0, 1.0, 0.0
            elif s < Lx + Ly:
                px, py, hx, hy = lx1, ly0 + (s - Lx), 0.0, 1.0
            elif s < 2 * Lx + Ly:
                px, py, hx, hy = lx1 - (s - Lx - Ly), ly1, -1.0, 0.0
            else:
                px, py, hx, hy = lx0, ly1 - (s - 2 * Lx - Ly), 0.0, -1.0
            tx, ty = (-hy, hx) if pd["bt"] > 0.0 else (hx, hy)   # turn to the shop (left) while browsing
            vx, vy = pd["hv"]
            vx += (tx - vx) * 0.12; vy += (ty - vy) * 0.12
            m = math.hypot(vx, vy) or 1.0
            pd["hv"] = (vx / m, vy / m)
            # ramp the gait amplitude up while moving, down while stopped
            pd["amp"] += ((1.0 if adv > 0.004 else 0.0) - pd["amp"]) * 0.14
            pd["x"] = px; pd["y"] = py
            # settled into window-shopping (stopped, gait faded, facing the shop):
            # nothing visibly changes, so skip all scene writes until walking resumes
            if pd["bt"] > 0.0 and pd["amp"] < 0.02 and abs(vx / m - tx) + abs(vy / m - ty) < 0.02:
                continue
            # write pose+limbs at half cadence, staggered by index (the walk math
            # above still advances every step, so motion stays exact — a ped just
            # renders its pose at ~15.6 Hz, which reads fine at walking speed)
            if (step_n + pi) % 2 == 0:
                ph = pd["dist"] * STEP_K
                sw = math.sin(ph) * pd["amp"]
                if pd["lf"]:
                    pd["lf"].setSFRotation([0.0, 1.0, 0.0, LEG_AMP * sw])
                    pd["lb"].setSFRotation([0.0, 1.0, 0.0, -LEG_AMP * sw])
                    pd["al"].setSFRotation([0.0, 1.0, 0.0, -ARM_AMP * sw])
                    pd["ar"].setSFRotation([0.0, 1.0, 0.0, ARM_AMP * sw])
                pd["tf"].setSFVec3f([px, py, -0.04 + 0.04 * pd["amp"] * abs(math.cos(ph))])
                pd["rf"].setSFRotation([0.0, 0.0, 1.0, math.atan2(pd["hv"][1], pd["hv"][0])])

        # ---- city bus: follow the ring route, pull up (dwell) at each stop ----
        if bus:
            wp = bus["wp"]; n = len(wp)
            if bus["dwell"] > 0.0:
                bus["dwell"] -= dt
            else:
                tgt = wp[bus["i"]]
                dx, dy = tgt[0] - bus["px"], tgt[1] - bus["py"]
                dl = math.hypot(dx, dy); st = bus["speed"] * dt
                if dl <= st + 1e-6:
                    bus["px"], bus["py"] = tgt[0], tgt[1]
                    if tgt[2] > 0:
                        bus["dwell"] = float(tgt[2])
                    bus["i"] = (bus["i"] + 1) % n
                else:
                    bus["px"] += dx / dl * st; bus["py"] += dy / dl * st
            tgt = wp[bus["i"]]
            dx, dy = tgt[0] - bus["px"], tgt[1] - bus["py"]; dl = math.hypot(dx, dy) or 1.0
            vx, vy = bus["hv"]; vx += (dx / dl - vx) * 0.1; vy += (dy / dl - vy) * 0.1
            m = math.hypot(vx, vy) or 1.0; bus["hv"] = (vx / m, vy / m)
            bus["tf"].setSFVec3f([bus["px"], bus["py"], 0.0])
            bus["rf"].setSFRotation([0.0, 0.0, 1.0, math.atan2(bus["hv"][1], bus["hv"][0])])

        # ---- crossing pedestrians: cross a zebra only when that road's cars are stopped ----
        for cr in crossers:
            cur = cr["A"] if cr["at"] == 0 else cr["B"]
            tgt = cr["B"] if cr["at"] == 0 else cr["A"]
            adv = 0.0
            if cr["moving"]:
                dx, dy = tgt[0] - cr["px"], tgt[1] - cr["py"]; dl = math.hypot(dx, dy)
                st = CROSS_SPEED * dt
                if dl <= st:
                    cr["px"], cr["py"] = tgt[0], tgt[1]; cr["moving"] = False; cr["at"] = 1 - cr["at"]; adv = dl
                else:
                    cr["px"] += dx / dl * st; cr["py"] += dy / dl * st; adv = st
                cr["dist"] += adv
            elif green_axis == cr["start_green"] and phase_t < 3.5:
                cr["moving"] = True              # light just went safe -> step off the kerb
            dx, dy = tgt[0] - cur[0], tgt[1] - cur[1]; dl = math.hypot(dx, dy) or 1.0
            hx, hy = dx / dl, dy / dl
            cr["amp"] += ((1.0 if adv > 0.004 else 0.0) - cr["amp"]) * 0.14
            # waiting at the kerb with the gait faded: skip all scene writes
            if not cr["moving"] and cr["amp"] < 0.02:
                continue
            ph = cr["dist"] * STEP_K
            sw = math.sin(ph) * cr["amp"]
            if cr["lf"]:
                cr["lf"].setSFRotation([0.0, 1.0, 0.0, LEG_AMP * sw])
                cr["lb"].setSFRotation([0.0, 1.0, 0.0, -LEG_AMP * sw])
                cr["al"].setSFRotation([0.0, 1.0, 0.0, -ARM_AMP * sw])
                cr["ar"].setSFRotation([0.0, 1.0, 0.0, ARM_AMP * sw])
            cr["tf"].setSFVec3f([cr["px"], cr["py"], -0.04 + 0.04 * cr["amp"] * abs(math.cos(ph))])
            cr["rf"].setSFRotation([0.0, 0.0, 1.0, math.atan2(hy, hx)])

        # ---- dog on a leash: trail 1.5 m behind its walker ----
        if dog:
            lead = peds[dog["ped"]]
            hx, hy = lead["hv"]
            dx = lead["x"] - hx * 1.5 - hy * 0.4
            dy = lead["y"] - hy * 1.5 + hx * 0.4
            vx, vy = dog["hv"]; vx += (hx - vx) * 0.15; vy += (hy - vy) * 0.15
            m = math.hypot(vx, vy) or 1.0; dog["hv"] = (vx / m, vy / m)
            dog["tf"].setSFVec3f([dx, dy, 0.0])
            dog["rf"].setSFRotation([0.0, 0.0, 1.0, math.atan2(dog["hv"][1], dog["hv"][0])])

        step_n += 1
        if stats_fh and step_n % max(1, int(1.0 / dt)) == 0:
            mind = BIG
            for i in range(len(cars)):
                for k in range(i + 1, len(cars)):
                    dx = cars[i]["pos"][0] - cars[k]["pos"][0]
                    dy = cars[i]["pos"][1] - cars[k]["pos"][1]
                    mind = min(mind, math.hypot(dx, dy))
            mean_v = sum(c["moved"] for c in cars) / max(1, len(cars)) / dt
            turning = sum(1 for c in cars if c["mode"] == "arc")
            stats_fh.write("%.1f,%s,%d,%.2f,%.2f,%d,%.2f\n" % (
                step_n * dt, green_axis or "ALLRED", len(cars), mind, mean_v, turning,
                time.time() - wall0)); stats_fh.flush()


if __name__ == "__main__":
    try:
        main()
    except Exception:
        import traceback
        tb = traceback.format_exc()
        sp = os.environ.get("CITY_TRAFFIC_STATS")
        if sp:
            try:
                with open(sp + ".err", "w") as fh:
                    fh.write(tb)
            except OSError:
                pass
        print("[city_traffic] CRASH:\n" + tb, flush=True)
        raise
