# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Emit an OmniSim .wbt that previews a hill-walk ghost: the matching hill
terrain (from the ghost's own HillProfile params) + a translucent visual-only
robot driven by the hill_ghost_preview controller. The hill geometry is the SAME
HillProfile the ghost was generated against, so the hologram's feet land on the
shown surface.

  python projects/policies/research/shadowing/make_hill_preview_world.py --robot b2
  python projects/policies/research/shadowing/make_hill_preview_world.py --robot spot
"""
import argparse
import os
import sys

import numpy as np

REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..", ".."))
sys.path.insert(0, REPO)
from projects.policies.research.shadowing.hill_terrain import HillProfile  # noqa: E402

GHOST_URDF = {
    "b2": "../../robots/unitree/b2/urdf/b2_ghost.urdf",
    "spot": "../../robots/boston_dynamics/spot/urdf/spot_ghost.urdf",
    "go2": "../../robots/unitree/go2/urdf/go2_ghost.urdf",
}
REAL_URDF = {
    "b2": "../../robots/unitree/b2/urdf/b2.urdf",
    "spot": "../../robots/boston_dynamics/spot/urdf/spot.urdf",
    "go2": "../../robots/unitree/go2/urdf/go2.urdf",
}
DEPLOY_CTRL = {"b2": "b2_walk_deploy", "spot": "spot_walk_deploy", "go2": "go2_walk_deploy"}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--robot", choices=list(GHOST_URDF), default="b2")
    ap.add_argument("--ghost", default=None)
    ap.add_argument("--shot", action="store_true",
                    help="add a camera-bot (hill_shot) to photograph the ghost headlessly")
    ap.add_argument("--deploy", action="store_true",
                    help="emit the DEPLOY world: real Newton robot on a COLLIDABLE hill "
                         "+ a translucent ghost alongside (run with OMNISIM_NEWTON_STATICS=1)")
    ap.add_argument("--out", default=None)
    a = ap.parse_args()
    ghost = a.ghost or os.path.join(REPO, "projects/policies/research/shadowing/ghosts", f"{a.robot}_hill_ghost.npz")
    suffix = "hill_deploy" if a.deploy else ("hill_shot" if a.shot else "hill_ghost_preview")
    out = a.out or os.path.join(REPO, "projects/policies/worlds", f"{a.robot}_{suffix}.wbt")

    g = np.load(ghost, allow_pickle=True)
    hp = HillProfile(grade_deg=float(g["hill_grade_deg"]), approach=float(g["hill_approach"]),
                     ramp_run=float(g["hill_ramp_run"]), crest=float(g["hill_crest"]),
                     fillet=float(g["hill_fillet"]))
    ride = float(g["ride"])
    R = a.robot.upper()
    hill = hp.wbt_nodes(name="hill", color="0.42 0.36 0.28", collidable=a.deploy)
    follow = f"{a.robot}" if a.deploy else f"{a.robot}_ghost"
    contact = ("""  contactProperties [
    ContactProperties { material1 "default" material2 "default" coulombFriction [ 2.0 ] bounce 0.0 }
  ]
""" if a.deploy else "")

    ghost_node = f"""DEF {R}_GHOST URDFRobot {{
  url "{GHOST_URDF[a.robot]}"
  translation 0 {1.6 if a.deploy else 0.0} {ride:.3f}
  name "{a.robot}_ghost"
  supervisor TRUE
  controller "hill_ghost_preview"
  staticBase TRUE
}}"""
    if a.deploy:
        # The PHYSICALLY-SIMULATED robot (Newton) shadows the ghost up the hill;
        # the translucent ghost walks the IDEAL beside it. Run with
        # OMNISIM_NEWTON_STATICS=1 so the hill boxes are collidable statics.
        robots = f"""DEF {R}_REAL URDFRobot {{
  url "{REAL_URDF[a.robot]}"
  translation 0 0 {ride:.3f}
  name "{a.robot}"
  supervisor TRUE
  controller "{DEPLOY_CTRL[a.robot]}"
  physicsBackend "newton"
}}
{ghost_node}"""
    else:
        robots = ghost_node

    title = f"{R} hill-walk {'DEPLOY (real + ghost)' if a.deploy else 'ghost (preview)'}"
    w = f"""#VRML_SIM R2025a utf8

# {R} hill-walk {'DEPLOY' if a.deploy else 'GHOST preview'} -- generated by
# make_hill_preview_world.py from the ghost's HillProfile; do not hand-edit.

EXTERNPROTO "omnisim://projects/objects/floors/protos/RectangleArena.proto"
EXTERNPROTO "omnisim://projects/objects/backgrounds/protos/OmniSimSky.proto"
EXTERNPROTO "omnisim://projects/objects/lights/protos/OmniSimSun.proto"
EXTERNPROTO "omnisim://projects/objects/lights/protos/OmniSimSunMarker.proto"

WorldInfo {{
  basicTimeStep 16
  title "{title}"
{contact}}}
Viewpoint {{
  orientation -0.32 0.34 0.88 1.66
  position -2.2 -4.5 2.6
  follow "{follow}"
  followType "Tracking Shot"
  followSmoothness 0.25
}}
OmniSimSky {{ }}
DEF SUN OmniSimSun {{ }}
DEF SUN_MARKER OmniSimSunMarker {{ }}

RectangleArena {{
  floorSize 60 8
  wallHeight 0.05
  floorAppearance PBRAppearance {{ baseColor 0.20 0.22 0.24 roughness 0.95 metalness 0 }}
}}

# ---- hill terrain (matches the ghost's HillProfile) ----
{hill}

{robots}
"""
    if a.shot:
        w += f"""
DEF CAMBOT Robot {{
  translation -1 -4.6 1.5
  name "cambot"
  controller "hill_shot"
  supervisor TRUE
  children [ Camera {{ name "cam" width 1280 height 720 fieldOfView 0.9 }} ]
}}
"""
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as f:
        f.write(w)
    print(f"[make-hill-preview] wrote {os.path.relpath(out, REPO)}  "
          f"({len(hp._boxes())} hill boxes, crest {hp.rise:.2f} m)")


if __name__ == "__main__":
    main()
