# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by tools/gen_fleet.py — do not hand-edit.
"""Fleet course: shared ref + obstacles, one route per platform."""

REF_LAT = 40.67
REF_LON = -73.94
REF_ALT = 0.0

ROUTE_HUSKY = [
    (-10.0, -14.0, 'h1'),
    (6.0, -16.0, 'h2'),
    (20.0, -12.0, 'h3'),
    (28.0, -15.0, 'h4'),
]
ROUTE_JACKAL = [
    (-10.0, 14.0, 'j1'),
    (6.0, 16.0, 'j2'),
    (20.0, 12.0, 'j3'),
    (28.0, 15.0, 'j4'),
]
ROUTE_ENU = ROUTE_HUSKY  # default

OBSTACLES = [
    (-21.70, -12.37, 0.35),
    (-18.10, -16.11, 0.4),
    (-14.50, -15.86, 0.35),
    (-4.50, -15.47, 0.7),
    (-1.36, -16.35, 0.4),
    (1.81, -17.00, 0.7),
    (10.41, -12.87, 0.8),
    (13.43, -12.86, 0.8),
    (17.01, -14.77, 0.8),
    (23.37, -11.53, 0.8),
    (24.08, -14.49, 0.8),
    (-21.70, 16.01, 0.8),
    (-18.10, 11.86, 0.8),
    (-14.50, 11.89, 0.4),
    (-4.54, 15.84, 0.4),
    (-1.08, 14.16, 0.8),
    (1.90, 16.29, 0.45),
    (11.33, 16.12, 0.7),
    (14.02, 14.92, 0.4),
    (16.02, 11.32, 0.4),
    (23.29, 11.73, 0.7),
    (25.25, 16.24, 0.4),
]
