# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by tools/gen_offroad_world.py — do not hand-edit.
"""Off-road course data shared by the controller and the plot tools."""

REF_LAT = 40.67
REF_LON = -73.94
REF_ALT = 0.0
START = (-25.0, -25.0)

# (east_m, north_m, name)
ROUTE_ENU = [
    (-8.0, -18.0, 'south_ridge'),
    (18.0, -20.0, 'south_post'),
    (24.0, 8.0, 'east_bend'),
    (-4.0, 20.0, 'north_glade'),
]

# (x_m, y_m, radius_m) discs for the modelled range sensor
OBSTACLES = [
    (-20.32, -24.28, 0.7),
    (-17.73, -23.34, 0.7),
    (-15.38, -21.81, 0.7),
    (-12.65, -21.20, 0.7),
    (-9.77, -20.95, 0.7),
    (-1.45, -17.84, 0.7),
    (2.30, -20.07, 0.7),
    (6.36, -18.36, 0.7),
    (10.15, -20.09, 0.7),
    (13.94, -21.81, 0.7),
    (18.01, -12.68, 0.7),
    (21.06, -8.94, 0.7),
    (21.96, -4.74, 0.7),
    (23.24, -0.62, 0.7),
    (21.67, 4.11, 0.7),
    (17.59, 12.38, 0.7),
    (13.10, 13.50, 0.7),
    (9.07, 15.70, 0.7),
    (4.99, 17.78, 0.7),
    (-0.35, 16.92, 0.7),
    (15.52, -1.93, 0.7),
    (23.71, -7.75, 0.7),
    (-14.09, -17.93, 0.7),
    (-11.19, -0.27, 0.7),
    (-8.77, -2.87, 0.7),
    (6.10, -23.90, 0.7),
    (-8.84, 24.26, 0.7),
    (-4.38, 25.87, 0.7),
]
