# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by tools/gen_city_nav.py — do not hand-edit.
"""City pedestrian course: sidewalk waypoints + a traffic crossing."""

REF_LAT = 40.67
REF_LON = -73.94
REF_ALT = 0.0
START = (5.0, -24.5)

ROUTE_ENU = [
    (14.0, -24.5, 'sidewalk'),
    (22.0, -24.5, 'approach'),
    (33.0, -24.5, 'crossed'),
    (40.0, -24.5, 'east_end'),
]
OBSTACLES = []  # buildings/cars are camera-detected; none scored statically

# (px, py, safe_gap, approach, commit) — wait for a gap before crossing
CROSSINGS = [(-24.5, 31.0, 6.0, 23.5, 26.0, 6.0)]

# Global route graph (deploy-with-reroute).
GRAPH_NODES = {'AN': (-31.0, -24.5), 'BN': (31.0, -24.5), 'AS': (-31.0, -37.5), 'BS': (31.0, -37.5), 'G': (40.0, -24.5)}
GRAPH_EDGES = [('AN', 'BN', 'walk', {'axis': 'x', 'lane': -24.5}), ('AS', 'BS', 'walk', {'axis': 'x', 'lane': -37.5}), ('AN', 'AS', 'cross', {'axis': 'y', 'lane': -31.0, 'road': -31.0}), ('BN', 'BS', 'cross', {'axis': 'y', 'lane': 31.0, 'road': -31.0}), ('BN', 'G', 'walk', {'axis': 'x', 'lane': -24.5})]
START_NODE = 'AN'
DEST_NODE = 'G'
