# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by tools/gen_world.py — do not hand-edit.
"""Populated-world course data (route + scored obstacle discs)."""

REF_LAT = 40.67
REF_LON = -73.94
REF_ALT = 0.0
START = (-26.0, -22.0)

ROUTE_ENU = [
    (-8.0, -16.0, 'south_field'),
    (20.0, -18.0, 'east_marker'),
    (22.0, 8.0, 'ridge_bend'),
    (0.0, 16.0, 'pasture_gate'),
    (-22.0, 10.0, 'west_stand'),
]

# (x, y, radius) collision discs for scoring (analyze_run.py)
OBSTACLES = [
    (-21.42, -18.93, 0.8),
    (-17.59, -20.84, 0.8),
    (-15.85, -16.44, 0.45),
    (-11.77, -19.09, 0.7),
    (-0.22, -17.41, 0.4),
    (4.49, -14.52, 0.45),
    (8.66, -19.15, 0.4),
    (13.23, -18.24, 0.7),
    (18.85, -10.59, 0.6),
    (22.32, -6.67, 0.4),
    (20.11, -2.32, 0.8),
    (22.23, 1.71, 0.8),
    (16.66, 12.49, 0.45),
    (12.71, 12.58, 0.4),
    (9.21, 13.92, 0.4),
    (4.60, 12.20, 0.7),
    (-6.37, 15.10, 0.35),
    (-10.17, 15.16, 0.8),
    (-13.80, 14.60, 0.8),
    (-16.37, 10.15, 0.8),
    (16.71, -21.21, 0.7),
    (-11.33, -31.39, 0.8),
    (15.48, -27.28, 0.8),
    (12.42, -31.56, 0.8),
    (17.82, -24.89, 0.4),
    (-18.70, -11.65, 0.45),
]
