# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Generated by tools/gen_swarm.py — do not hand-edit.
"""Swarm course: shared ref + static obstacles, one route per robot."""

REF_LAT = 40.67
REF_LON = -73.94
REF_ALT = 0.0

ROUTE_N1 = [
    (32.0, -6.0, 'a1'),
]
ROUTE_N2 = [
    (-32.0, -6.0, 'b1'),
]
ROUTE_N3 = [
    (32.0, 6.0, 'c1'),
]
ROUTE_N4 = [
    (-32.0, 6.0, 'd1'),
]
ROUTE_ENU = ROUTE_N1  # default

OBSTACLES = [
    (-22.00, -4.50, 0.7),
    (22.00, -7.50, 0.8),
    (-22.00, 7.50, 0.8),
    (22.00, 4.50, 0.4),
    (-26.00, -7.20, 0.35),
    (26.00, 6.20, 0.35),
]
