# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Generate the G1 stair-climb worlds from the shared StairProfile so the ghost,
the in-engine trainer terrain, and the deploy world all agree on the geometry.

  preview : ghost-only hologram climbing the staircase (owner sign-off render)
  train   : G1 (newton) + staircase, minimal -- the recipe trainer batches THIS
            world's compiled model (put_model), so these step boxes ARE the
            training terrain (train == deploy).
  deploy  : G1 (newton) + staircase + ghost hologram + visible harness rig, the
            BATON climb demo world (walk in from the flat, climb, stand on top).

Stairs are collidable Solid Box nodes emitted by StairProfile.wbt_nodes() and are
NEWTON-backed by living in a newtonSolver world (the robot is physicsBackend
"newton"); an ODE prop would have no cross-backend contact with the robot.

  python projects/policies/worlds/make_stair_worlds.py [--riser 0.10 --going 0.26
      --n-steps 5] [--which preview,train,deploy]
"""
from __future__ import annotations

import argparse
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
RT = os.environ.get("OMNISIM_HOME", os.path.abspath(os.path.join(HERE, "..", "..", "..")))
sys.path.insert(0, os.path.join(RT, "projects", "policies", "research", "shadowing"))
from hill_terrain import StairProfile  # noqa: E402

GHOST = "../../controllers/g1_ghost/ghost_stair_climb_lut.json"     # rel to a world in projects/policies/worlds
GHOST_ABS = os.path.join(RT, "projects/policies/controllers/g1_ghost/ghost_stair_climb_lut.json").replace("\\", "/")

HEADER = """#VRML_SIM R2025a utf8

# {title}
# GENERATED by projects/policies/worlds/make_stair_worlds.py -- do not hand-edit.
# Staircase: {ns} steps, riser {riser:.2f} m, going {going:.2f} m, climb {rise:.2f} m,
# from the shared StairProfile (train == deploy geometry).

EXTERNPROTO "omnisim://projects/objects/floors/protos/RectangleArena.proto"
EXTERNPROTO "omnisim://projects/objects/backgrounds/protos/OmniSimSky.proto"
EXTERNPROTO "omnisim://projects/objects/lights/protos/OmniSimSun.proto"
EXTERNPROTO "omnisim://projects/objects/lights/protos/OmniSimSunMarker.proto"

WorldInfo {{
  newtonSolver "mujoco"
  basicTimeStep 16
  title "{title}"
  contactProperties [
    ContactProperties {{ material1 "default" material2 "default" coulombFriction [ 1.5 ] bounce 0.0 bounceVelocity 0.5 maxContactJoints 40 }}
  ]
}}
Viewpoint {{
  orientation {vp_ori}
  position {vp_pos}
  follow "{follow}"
  followType "Tracking Shot"
}}
OmniSimSky {{ }}
DEF SUN OmniSimSun {{ }}
DEF SUN_MARKER OmniSimSunMarker {{ }}
RectangleArena {{
  floorSize {floor}
  wallHeight 0.05
  floorAppearance PBRAppearance {{ baseColor 0.18 0.20 0.22 roughness 0.95 metalness 0 }}
}}
"""

GHOST_NODE = """DEF G1_GHOST URDFRobot {{
  url "../../robots/unitree/g1/urdf/g1_23dof_ghost.urdf"
  translation 0 1.1 {gz:.3f}
  name "g1_ghost"
  supervisor TRUE
  controller "g1_ghost"
  controllerArgs [ "{lut}" ]
  staticBase TRUE
  physicsBackend "ode"
}}
"""

ROBOT_NODE = """DEF G1_REAL URDFRobot {{
  url "../../robots/unitree/g1/urdf/g1_23dof_omnisim.urdf"
  translation 0 0 {sz:.3f}
  name "g1"
  supervisor TRUE
  controller "humanoid_stand_deploy"
  physicsBackend "newton"
}}
"""

HARNESS_VIS = """DEF HARNESS_RIG Robot {
  name "harness_rig"
  supervisor TRUE
  controller "harness_rig"
}
DEF HARNESS_LINE Solid {
  translation 0 0 1.6
  name "harness_line"
  children [ Shape { appearance PBRAppearance { baseColor 0.95 0.80 0.15 transparency 0.35 roughness 0.6 metalness 0 }
    geometry DEF HARNESS_CYL Cylinder { radius 0.012 height 1.6 } } ]
}
DEF HARNESS_HOOK Solid {
  translation 0 0 2.4
  name "harness_hook"
  children [ Shape { appearance PBRAppearance { baseColor 0.95 0.80 0.15 transparency 0.1 roughness 0.4 metalness 0.6 }
    geometry Box { size 0.22 0.22 0.06 } } ]
}
"""


def _header(title, follow, floor="12 8", vp_pos="1.4 -4.2 1.9", vp_ori="-0.30 0.30 0.905 1.66", **kw):
    return HEADER.format(title=title, follow=follow, floor=floor, vp_pos=vp_pos, vp_ori=vp_ori, **kw)


def gen(which, sp, a):
    ns, riser, going, rise = sp.n_steps, sp.riser, sp.going, sp.rise
    stairs = sp.wbt_nodes(collidable=True)
    gz = sp.riser * 0 + 0.68           # ghost spawn z (controller overrides from root_lut)
    sz = 0.72                          # robot spawn z on the flat before the stairs
    common = dict(ns=ns, riser=riser, going=going, rise=rise)
    sfx = getattr(a, "suffix", "")     # optional filename suffix (e.g. _solo) for a dedicated variant

    if which == "preview":
        title = "G1 stair-climb GHOST preview (hologram climbing %d steps)" % ns
        body = _header(title, "g1_ghost", vp_pos="1.4 -3.6 1.7", **common)
        body += "\n" + stairs + "\n\n" + GHOST_NODE.format(gz=gz, lut=GHOST_ABS)
        out = os.path.join(HERE, "g1_climb_stairs_preview%s.wbt" % sfx)
    elif which == "train":
        title = "G1 stair-climb TRAIN (robot + staircase; recipe batches this model)"
        # ROBOT FIRST, then the stairs: the stair Solids are Newton static bodies, so emitting them
        # before the robot shifts the robot's Newton body ids and breaks the deploy harness's
        # HARNESS_NEWTON_BODY=5 base resolution (the flagship world has the robot first). The recipe
        # zeroes spawn x, so the robot starts at x=0 at the base.
        body = _header(title, "g1", vp_pos="1.2 -3.6 1.7", **common)
        body += "\n" + ROBOT_NODE.format(sz=sz) + "\n\n" + stairs
        out = os.path.join(HERE, "g1_climb_stairs%s.wbt" % sfx)
    elif which == "deploy":
        title = "G1 stair-climb DEPLOY (BATON walk->climb->stand puppet demo)"
        body = _header(title, "g1", floor="16 8", vp_pos="2.0 -4.5 1.9", **common)
        body += "\n" + ROBOT_NODE.format(sz=sz)              # robot FIRST (harness base id = 5)
        body += "\n" + GHOST_NODE.format(gz=gz, lut=GHOST_ABS)  # ghost is ODE (own backend, no id shift)
        body += "\n" + HARNESS_VIS
        body += "\n" + stairs                                # Newton static stairs AFTER the robot
        out = os.path.join(HERE, "g1_climb_stairs_puppet%s.wbt" % sfx)
    else:
        raise SystemExit("unknown world %r" % which)

    with open(out, "w", encoding="utf-8") as f:
        f.write(body)
    print("wrote %s  (%d step boxes, climb %.2f m over %.2f m)" %
          (out, ns + 1, rise, ns * going))
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--riser", type=float, default=0.10)
    ap.add_argument("--going", type=float, default=0.26)
    ap.add_argument("--n-steps", type=int, default=5)
    ap.add_argument("--x-start", type=float, default=0.12)
    ap.add_argument("--width", type=float, default=4.0, help="staircase y-extent (ghost climbs at y=1.1)")
    ap.add_argument("--which", default="preview,train,deploy")
    ap.add_argument("--suffix", default="", help="append to output filenames (e.g. _solo) for a dedicated variant")
    a = ap.parse_args()
    sp = StairProfile(riser=a.riser, going=a.going, n_steps=a.n_steps,
                      x_start=a.x_start, width=a.width)
    for w in a.which.split(","):
        gen(w.strip(), sp, a)


if __name__ == "__main__":
    main()
