# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""One-shot generator for omniarm6_bin_picking.omniworld: a random, full bin of 36 cubes
(18 red / 18 blue) dumped at jittered positions + random orientations, a tall
collider bin, two collider sort-trays, and a top-down recognition camera."""
import random
random.seed(7)
RED = (0.88, 0.18, 0.16)
BLUE = (0.16, 0.36, 0.88)

HEADER = '''#OMNISIM R2025a utf8

# OmniLink — OMNIARM6 BIN PICKING + COLOR SORT (camera-driven, random full bin)
# A OMNIARM6 + a real SUCTION (vacuum) cup empties a box that has been FILLED with
# 36 cubes dumped in randomly (jittered positions, random orientations, stacked
# into a pile) and SORTS them by colour into two trays. The vacuum cup grips each
# cube's TOP face from directly above, so dense packing / rolling / jaw geometry
# stop mattering -- the pile empties top-down with no shaking. A top-down camera
# (Recognition node) detects the cubes; its controller publishes the visible
# cube ids+colours to customData, and the arm picks the cubes the camera sees
# (occlusion => the top of the pile), reading each cube's pose from the scene.
#
# Newton + MuJoCo solver (friction grasp). Bin + tray walls are real Newton
# static colliders (launch with OMNISIM_NEWTON_STATICS=1) so the gripper can't
# pass through them. Static colliders are MuJoCo-compatible after the 2026-06-05
# OmNewtonBackend fix (fixed-joint weld at spawn pose).
#
# Generated by _genworld.py (seed 7). Headless verify:
#   OMNISIM_NEWTON_STATICS=1 BINPICK_AUTOQUIT=1 python scripts/dev/headless_runner.py \\
#     projects/samples/demos/worlds/flagship/omniarm6_bin_picking.omniworld --duration 1200

EXTERNPROTO "omnisim://projects/samples/demos/protos/OmniLinkStage.proto"
EXTERNPROTO "omnisim://projects/objects/backgrounds/protos/OmniSimSky.proto"
EXTERNPROTO "omnisim://projects/objects/lights/protos/OmniSimSun.proto"
EXTERNPROTO "omnisim://projects/objects/lights/protos/OmniSimSunMarker.proto"

WorldInfo {
  basicTimeStep 16
  title "OmniLink — OMNIARM6 bin picking + colour sort (camera, random fill)"
  newtonSolver "mujoco"
  contactProperties [
    ContactProperties { material1 "default" material2 "default" coulombFriction [ 5 ] bounce 0 softCFM 0.0003 }
  ]
}
Viewpoint { orientation -0.5573 0.5773 0.5973 2.10 position 1.95 -1.75 1.5 }
OmniSimSky { }
DEF SUN OmniSimSun { }
DEF SUN_MARKER OmniSimSunMarker { }
OmniLinkStage { floorSize 4 4 }

DEF OMNIARM6 URDFRobot {
  url "../../../../robots/omnisim/omniarm6/omniarm6_suction.urdf"
  translation 0 0 0
  name "omniarm6"
  supervisor TRUE
  staticBase TRUE
  physicsBackend "newton"
  controller "omniarm6_bin_picking"
}
# The suction (vacuum) cup is a real tool link in omniarm6_suction.urdf (flared
# rubber cup on the flange, NO fingers), so it rides the wrist rigidly -- no
# separate visual node to pin. The pick is a vacuum weld in the controller.

# ── Top-down recognition camera over the bin ────────────────────────
DEF BIN_CAM Robot {
  translation 0.46 0 1.15
  children [
    Camera {
      name "bin_camera"
      rotation 0 1 0 1.5708
      width 320
      height 320
      fieldOfView 0.6
      recognition Recognition { maxRange 3 occlusion 1 frameColor 0 1 0 frameThickness 2 }
    }
  ]
  name "bin_cam"
  controller "bin_camera"
}

# ── The BOX: a MOVABLE dynamic bin (floor + 4 walls on ONE free Newton body) so
# the robot can GRAB it by a wall and SHAKE/TILT it to tumble stuck cubes into
# reachable spots (singulation) when picking stalls. Heavy + a low CG so reaching
# in to pick doesn't shove it; only a deliberate grab moves it. Launch with
# OMNISIM_NEWTON_COMPOUND_COLLIDERS=1 so every wall + the floor is a real collider.
DEF MOVABLE_BIN Solid {
  translation 0.46 0 0.0
  rotation 0 0 1 0
  physicsBackend "newton"
  children [
    Transform { translation 0 0 0.011 children [ DEF BFLOOR_SH Shape { appearance PBRAppearance { baseColor 0.28 0.31 0.36 roughness 0.85 metalness 0.2 } geometry Box { size 0.42 0.42 0.022 } } ] }
    Transform { translation -0.195 0 0.131 children [ DEF BWW_SH Shape { appearance PBRAppearance { baseColor 0.30 0.33 0.38 roughness 0.8 metalness 0.3 } geometry Box { size 0.03 0.42 0.22 } } ] }
    Transform { translation 0.195 0 0.131 children [ DEF BWE_SH Shape { appearance PBRAppearance { baseColor 0.30 0.33 0.38 roughness 0.8 metalness 0.3 } geometry Box { size 0.03 0.42 0.22 } } ] }
    Transform { translation 0 -0.195 0.131 children [ DEF BWS_SH Shape { appearance PBRAppearance { baseColor 0.30 0.33 0.38 roughness 0.8 metalness 0.3 } geometry Box { size 0.42 0.03 0.22 } } ] }
    Transform { translation 0 0.195 0.131 children [ DEF BWN_SH Shape { appearance PBRAppearance { baseColor 0.30 0.33 0.38 roughness 0.8 metalness 0.3 } geometry Box { size 0.42 0.03 0.22 } } ] }
  ]
  name "movable_bin"
  boundingObject Group { children [
    Transform { translation 0 0 0.011 children [ Box { size 0.42 0.42 0.022 } ] }
    Transform { translation -0.195 0 0.131 children [ Box { size 0.03 0.42 0.22 } ] }
    Transform { translation 0.195 0 0.131 children [ Box { size 0.03 0.42 0.22 } ] }
    Transform { translation 0 -0.195 0.131 children [ Box { size 0.42 0.03 0.22 } ] }
    Transform { translation 0 0.195 0.131 children [ Box { size 0.42 0.03 0.22 } ] }
  ] }
  physics Physics { density -1 mass 6.0 centerOfMass [ 0 0 0.015 ] }
}

# ── Output TRAYS — sorted destinations (low collider walls) ─────────
DEF RED_ZONE Solid { translation 0.30 -0.44 0.001 children [ Shape { appearance PBRAppearance { baseColor 0.85 0.18 0.16 roughness 1 metalness 0 transparency 0.35 } geometry Box { size 0.26 0.24 0.002 } } ] name "red_zone" }
DEF RED_W Solid { translation 0.1625 -0.44 0.025 physicsBackend "newton" children [ DEF RW_S Shape { appearance PBRAppearance { baseColor 0.70 0.20 0.18 roughness 0.8 } geometry Box { size 0.015 0.27 0.05 } } ] name "red_w" boundingObject USE RW_S }
DEF RED_E Solid { translation 0.4375 -0.44 0.025 physicsBackend "newton" children [ DEF RE_S Shape { appearance PBRAppearance { baseColor 0.70 0.20 0.18 roughness 0.8 } geometry Box { size 0.015 0.27 0.05 } } ] name "red_e" boundingObject USE RE_S }
DEF RED_S Solid { translation 0.30 -0.5675 0.025 physicsBackend "newton" children [ DEF RS_S Shape { appearance PBRAppearance { baseColor 0.70 0.20 0.18 roughness 0.8 } geometry Box { size 0.29 0.015 0.05 } } ] name "red_s" boundingObject USE RS_S }
DEF RED_N Solid { translation 0.30 -0.3125 0.025 physicsBackend "newton" children [ DEF RN_S Shape { appearance PBRAppearance { baseColor 0.70 0.20 0.18 roughness 0.8 } geometry Box { size 0.29 0.015 0.05 } } ] name "red_n" boundingObject USE RN_S }
DEF BLUE_ZONE Solid { translation -0.02 -0.44 0.001 children [ Shape { appearance PBRAppearance { baseColor 0.16 0.36 0.85 roughness 1 metalness 0 transparency 0.35 } geometry Box { size 0.26 0.24 0.002 } } ] name "blue_zone" }
DEF BLUE_W Solid { translation -0.1575 -0.44 0.025 physicsBackend "newton" children [ DEF BW_S Shape { appearance PBRAppearance { baseColor 0.18 0.28 0.70 roughness 0.8 } geometry Box { size 0.015 0.27 0.05 } } ] name "blue_w" boundingObject USE BW_S }
DEF BLUE_E Solid { translation 0.1175 -0.44 0.025 physicsBackend "newton" children [ DEF BE_S Shape { appearance PBRAppearance { baseColor 0.18 0.28 0.70 roughness 0.8 } geometry Box { size 0.015 0.27 0.05 } } ] name "blue_e" boundingObject USE BE_S }
DEF BLUE_S Solid { translation -0.02 -0.5675 0.025 physicsBackend "newton" children [ DEF BS_S Shape { appearance PBRAppearance { baseColor 0.18 0.28 0.70 roughness 0.8 } geometry Box { size 0.29 0.015 0.05 } } ] name "blue_s" boundingObject USE BS_S }
DEF BLUE_N Solid { translation -0.02 -0.3125 0.025 physicsBackend "newton" children [ DEF BN_S Shape { appearance PBRAppearance { baseColor 0.18 0.28 0.70 roughness 0.8 } geometry Box { size 0.29 0.015 0.05 } } ] name "blue_n" boundingObject USE BN_S }

# ── Cubes — dumped in randomly to fill the bin (18 red + 18 blue) ────
'''

cols = [0.34, 0.42, 0.50, 0.58]
rows = [-0.08, 0.0, 0.08]
zs = [0.05, 0.115, 0.18]
cells = [(x, y, z) for z in zs for y in rows for x in cols]   # 36
colors = ['red'] * 18 + ['blue'] * 18
random.shuffle(colors)


def rrot():
    ax = [random.uniform(-1, 1) for _ in range(3)]
    n = sum(a * a for a in ax) ** 0.5 or 1.0
    ax = [a / n for a in ax]
    ang = random.uniform(0.05, 0.22)
    return "%.3f %.3f %.3f %.3f" % (ax[0], ax[1], ax[2], ang)


parts = []
for i, (cx, cy, cz) in enumerate(cells, start=1):
    x = cx + random.uniform(-0.008, 0.008)
    y = cy + random.uniform(-0.008, 0.008)
    r, g, b = (RED if colors[i - 1] == 'red' else BLUE)
    parts.append(
        'DEF PART_%d Solid { translation %.4f %.4f %.3f rotation %s physicsBackend "newton" '
        'children [ DEF PART_%d_SHAPE Shape { appearance PBRAppearance { baseColor %s %s %s roughness 1 metalness 0 } '
        'geometry Box { size 0.05 0.05 0.05 } } ] name "part_%d" boundingObject USE PART_%d_SHAPE '
        'recognitionColors [ %s %s %s ] physics Physics { density -1 mass 0.06 } }'
        % (i, x, y, cz, rrot(), i, r, g, b, i, i, r, g, b))

out = HEADER + "\n".join(parts) + "\n"
path = "projects/samples/demos/worlds/flagship/omniarm6_bin_picking.omniworld"
open(path, "w", encoding="utf-8", newline="\n").write(out)
print("wrote %s : 36 cubes (%d red / %d blue)" % (path, colors.count('red'), colors.count('blue')))
