# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Emit deterministic-probe deploy worlds for a robot from its parity-probe spec.

Writes projects/policies/worlds/<robot>_parity_probe.wbt (welded base, lifted so the
feet clear the floor -> the chaos-free machine-precision lane) and
<robot>_parity_probe_free.wbt (free base on the ground -> realistic lane). Both
run the generic ``parity_probe`` controller with ``--robot <name>``.

    python scripts/dev/gen_parity_probe_world.py --robot h1
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO))
from projects.policies.research.backends import parity_probe_spec as PP  # noqa: E402

WORLDS = _REPO / "projects/policies/worlds"

HEADER = """#VRML_SIM R2025a utf8

# DETERMINISTIC PHYSICS PARITY PROBE -- {robot} ({lane} lane). GENERATED by
# scripts/dev/gen_parity_probe_world.py. Runs the generic parity_probe controller
# (NO RL): applies SPEC.targets(k) and dumps a per-tick trace; robot_parity_probe.py
# applies the SAME targets in the trainer; g1_parity_compare.py diffs them. See
# docs/developer/binary-parity-probe.md.{weldnote}

EXTERNPROTO "omnisim://projects/objects/backgrounds/protos/TexturedBackground.proto"
EXTERNPROTO "omnisim://projects/objects/backgrounds/protos/TexturedBackgroundLight.proto"
EXTERNPROTO "omnisim://projects/objects/floors/protos/RectangleArena.proto"
EXTERNPROTO "omnisim://projects/objects/backgrounds/protos/OmniSimSky.proto"
EXTERNPROTO "omnisim://projects/objects/lights/protos/OmniSimSun.proto"
EXTERNPROTO "omnisim://projects/objects/lights/protos/OmniSimSunMarker.proto"

WorldInfo {{
  newtonSolver "mujoco"
  basicTimeStep 16
  title "{robot} deterministic parity probe ({lane} base)"
  contactProperties [
    ContactProperties {{
      material1 "default"
      material2 "default"
      coulombFriction [ 1.5 ]
      bounce 0.0
      bounceVelocity 0.5
    }}
  ]
}}
Viewpoint {{
  orientation -0.5773 0.5773 0.5773 2.0944
  position 0 0 5
  follow ""
  followType "None"
}}
OmniSimSky {{ }}
DEF SUN OmniSimSun {{ }}
DEF SUN_MARKER OmniSimSunMarker {{ }}
RectangleArena {{
  floorSize 20 6
  wallHeight 0.05
  floorAppearance PBRAppearance {{
    baseColor 0.18 0.20 0.22
    roughness 0.95
    metalness 0
  }}
}}

URDFRobot {{
  url "{url}"
  translation 0 0 {z}
  name "{robot}"
  supervisor TRUE
  controller "parity_probe"
  controllerArgs [ "--robot" "{robot}" ]
  physicsBackend "newton"{weld}
}}
"""

WELDNOTE = ("\n# WELDED (staticBase): the base is pinned at its spawn pose and lifted "
            "{z:.2f} m\n# so the feet clear the floor -> NO contact -> pure articulation parity.")


def emit(robot: str):
    import os
    spec = PP.load(robot)
    url = os.path.relpath(spec.urdf, WORLDS).replace("\\", "/")
    lifted = round(spec.lifted_z(), 3)
    out = []
    # welded
    p = WORLDS / f"{robot}_parity_probe.wbt"
    p.write_text(HEADER.format(robot=robot, lane="welded", url=url, z=lifted,
                               weld="\n  staticBase TRUE",
                               weldnote=WELDNOTE.format(z=lifted)), encoding="utf-8")
    out.append(p)
    # free
    p = WORLDS / f"{robot}_parity_probe_free.wbt"
    p.write_text(HEADER.format(robot=robot, lane="free", url=url,
                               z=round(spec.spawn_z, 3), weld="", weldnote=""),
                 encoding="utf-8")
    out.append(p)
    return out


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--robot", required=True)
    args = ap.parse_args(argv)
    for p in emit(args.robot):
        print("wrote", p)
    return 0


if __name__ == "__main__":
    sys.exit(main())
