#!/usr/bin/env python3
# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Granular-physics measurement spike — companion to
docs/developer/granular-physics-plan.md.

Generates granular_sand_demo variants at parametric sphere counts,
runs each headless with --log-performance=<file>, parses the resulting
performance log, and emits a comparison table.

The goal is to confirm or refute the plan's diagnosis before any code
lands: where is wall-clock time *actually* being spent during the
active phase of a granular pile? Physics? Rendering? Loading?

Usage:

    python scripts/dev/granular_spike.py
        # default sweep: N = 100, 200, 400, 600 spheres, 15 s of sim each

    python scripts/dev/granular_spike.py --counts 200 600 1000 --duration 20

The script writes:
  - one .wbt per sweep value under tests/granular-spike/worlds/
  - one .perf log per sweep value under tests/granular-spike/logs/
  - one Markdown summary at tests/granular-spike/results.md
"""

from __future__ import annotations

import argparse
import math
import os
import random
import re
import subprocess
import sys
import time
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SPIKE_DIR = REPO_ROOT / "tests" / "granular-spike"
WORLDS_DIR = SPIKE_DIR / "worlds"
LOGS_DIR = SPIKE_DIR / "logs"

R = 0.05
SPACING = 0.105
PIT_HALF = 1.4
WALL_H = 1.0
WALL_T = 0.15

WORLD_TEMPLATE_HEADER = """#OMNISIM R2025a utf8

# Auto-generated by scripts/dev/granular_spike.py — do not edit by hand.
# Parametric granular_sand_demo variant for the Tier-1 measurement spike.
#   N = {n} spheres
#   basicTimeStep = {basic_time_step} ms
#   physicsDisableTime = {disable_time}
#   physicsDisableLinearThreshold = {disable_threshold}
#   physicsDisableAngularThreshold = {disable_threshold}

EXTERNPROTO "omnisim://projects/objects/floors/protos/Floor.proto"
EXTERNPROTO "omnisim://projects/appearances/protos/SandyGround.proto"
EXTERNPROTO "omnisim://projects/objects/apartment_structure/protos/Wall.proto"
EXTERNPROTO "omnisim://projects/appearances/protos/RoughConcrete.proto"

WorldInfo {{
  basicTimeStep {basic_time_step}
  physicsDisableTime {disable_time}
  physicsDisableLinearThreshold {disable_threshold}
  physicsDisableAngularThreshold {disable_threshold}
  contactProperties [
    ContactProperties {{
      material1 "sand_grain"
      material2 "sand_grain"
      coulombFriction [ 0.65 ]
      bounce 0.05
      bounceVelocity 0.02
    }}
    ContactProperties {{
      material1 "sand_grain"
      material2 "default"
      coulombFriction [ 0.7 ]
      bounce 0.0
    }}
  ]
}}
Viewpoint {{
  orientation 0 0.18 0.984 2.36
  position 4 -4 3
  near 0.05
  far 80
}}
Background {{
  skyColor [ 0.78 0.72 0.58 ]
}}
DirectionalLight {{
  direction 0.4 -0.5 -0.8
  intensity 3.0
  ambientIntensity 0.55
  castShadows TRUE
}}
Floor {{
  size 8 8
  tileSize 2 2
  appearance SandyGround {{ textureTransform TextureTransform {{ scale 4 4 }} }}
}}
Robot {{
  name "spike_quit_controller"
  controller "spike_quit"
  controllerArgs [ "{quit_steps}" ]
  supervisor TRUE
  synchronization FALSE
}}
"""


def grid_dims(n: int) -> tuple[int, int, int]:
    """Pick a roughly cubic NX*NY*NZ grid that yields >= n spheres."""
    side = max(2, int(round(n ** (1 / 3))))
    nx = ny = side
    nz = max(2, math.ceil(n / (nx * ny)))
    return nx, ny, nz


def write_world(path: Path, n: int, basic_time_step: int, disable_time: float, disable_threshold: float, quit_steps: int) -> int:
    random.seed(7)
    nx, ny, nz = grid_dims(n)
    drop_z = 1.6
    density = 1600
    mass = density * (4 / 3) * math.pi * R ** 3
    out: list[str] = [WORLD_TEMPLATE_HEADER.format(
        n=n,
        basic_time_step=basic_time_step,
        disable_time=disable_time,
        disable_threshold=disable_threshold,
        quit_steps=quit_steps,
    )]
    walls = [
        ("wall_N", (0,  PIT_HALF, WALL_H / 2), 0,      (PIT_HALF * 2 + WALL_T * 2, WALL_T, WALL_H)),
        ("wall_S", (0, -PIT_HALF, WALL_H / 2), 0,      (PIT_HALF * 2 + WALL_T * 2, WALL_T, WALL_H)),
        ("wall_E", ( PIT_HALF, 0, WALL_H / 2), 1.5708, (PIT_HALF * 2,                WALL_T, WALL_H)),
        ("wall_W", (-PIT_HALF, 0, WALL_H / 2), 1.5708, (PIT_HALF * 2,                WALL_T, WALL_H)),
    ]
    for name, (x, y, z), rot, (sx, sy, sz) in walls:
        out.append(
            f'Wall {{ name "{name}" translation {x} {y} {z:.3f} '
            f'rotation 0 0 1 {rot} size {sx} {sy} {sz} '
            'appearance RoughConcrete {} }\n'
        )
    written = 0
    for k in range(nz):
        for j in range(ny):
            for i in range(nx):
                if written >= n:
                    break
                x = (i - nx / 2 + 0.5) * SPACING + random.uniform(-0.005, 0.005)
                y = (j - ny / 2 + 0.5) * SPACING + random.uniform(-0.005, 0.005)
                z = drop_z + k * SPACING + random.uniform(0, 0.005)
                tint = 0.85 + random.uniform(-0.1, 0.05)
                r = max(0.0, min(1.0, 0.95 * tint))
                g = max(0.0, min(1.0, 0.78 * tint))
                b = max(0.0, min(1.0, 0.50 * tint))
                out.append(
                    f"DEF G_{written} Solid {{\n"
                    f"  translation {x:.4f} {y:.4f} {z:.4f}\n"
                    f"  children [\n"
                    f"    Shape {{\n"
                    f"      appearance PBRAppearance {{ baseColor {r:.3f} {g:.3f} {b:.3f} roughness 0.9 metalness 0.0 }}\n"
                    f"      geometry Sphere {{ radius {R} subdivision 1 }}\n"
                    f"    }}\n"
                    f"  ]\n"
                    f'  name "g{written}"\n'
                    f'  contactMaterial "sand_grain"\n'
                    f"  boundingObject Sphere {{ radius {R} subdivision 1 }}\n"
                    f"  physics Physics {{ density -1 mass {mass:.6f} }}\n"
                    f"}}\n"
                )
                written += 1
    path.write_text("".join(out), encoding="utf-8")
    return written


def find_omnisim_binary() -> Path:
    omnisim_home = Path(os.environ.get("OMNISIM_HOME", str(REPO_ROOT)))
    if sys.platform == "win32":
        for candidate in (
            omnisim_home / "msys64" / "mingw64" / "bin" / "omnisim-bin.exe",
            omnisim_home / "msys64" / "mingw64" / "bin" / "webots.exe",
        ):
            if candidate.exists():
                return candidate
    elif sys.platform == "darwin":
        c = omnisim_home / "Contents" / "MacOS" / "webots"
        if c.exists():
            return c
    else:
        for candidate in (omnisim_home / "bin" / "omnisim-bin", omnisim_home / "webots"):
            if candidate.exists():
                return candidate
    raise SystemExit(f"Could not find the omnisim binary under OMNISIM_HOME={omnisim_home}")


def run_headless(world: Path, log: Path, duration_s: int) -> tuple[int, float]:
    """Launch OmniSim headless on `world`, capture --log-performance to `log`,
    let it run for `duration_s` seconds of wall time, then SIGTERM.

    Returns (exit_code, wall_seconds).
    """
    binary = find_omnisim_binary()
    if log.exists():
        log.unlink()
    cmd = [
        str(binary),
        str(world),
        "--batch",
        "--mode=fast",
        "--no-rendering",
        "--minimize",
        "--stdout",
        "--stderr",
        f"--log-performance={log}",
    ]
    env = os.environ.copy()
    env.setdefault("OMNISIM_HOME", str(Path(os.environ.get("OMNISIM_HOME", str(REPO_ROOT)))))
    if sys.platform == "win32":
        env["PATH"] = str(binary.parent) + os.pathsep + env.get("PATH", "")
    # Allow generous wall time (15x sim duration) since heavy sims can run
    # well below real-time. The spike_quit supervisor calls simulationQuit
    # after the configured step count, which is what flushes the perf log.
    wall_budget = max(120, duration_s * 15)
    started = time.time()
    proc = subprocess.Popen(cmd, env=env, stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL)
    try:
        proc.wait(timeout=wall_budget)
        exit_code = proc.returncode
    except subprocess.TimeoutExpired:
        proc.terminate()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait(timeout=2)
        exit_code = proc.returncode if proc.returncode is not None else -1
    return exit_code, time.time() - started


_HEADER_RE = re.compile(r"<(\w+)\(ms\)>|<(mainFPS)>|<(mainTrianglesCount)>")


def parse_perf_log(path: Path) -> dict | None:
    """Parse an OmniSim performance log into a dict of {bucket: avg_ms}.

    The format produced by OmPerformanceLog::writeTotalValues writes a
    header line followed by an AVG row and a TOT row.
    """
    if not path.exists():
        return None
    text = path.read_text(errors="replace")
    lines = [ln for ln in text.splitlines() if ln.strip()]
    speed_factor = 0.0
    for ln in lines:
        m = re.match(r"Average speed factor:\s*([0-9.]+)", ln)
        if m:
            try:
                speed_factor = float(m.group(1))
            except ValueError:
                pass
            break
    header_idx = None
    for i, ln in enumerate(lines):
        if "<mainFPS>" in ln and "<mode>" in ln:
            header_idx = i
            break
    if header_idx is None:
        return None
    header = lines[header_idx]
    headers = re.findall(r"<([^>]+)>", header)
    # Drop the first two ("mode", "stepsCount") — they're handled separately.
    headers = headers[2:]
    avg_idx = None
    for i in range(header_idx + 1, len(lines)):
        if lines[i].strip().startswith("AVG"):
            avg_idx = i
            break
    if avg_idx is None:
        return None
    cells = lines[avg_idx].split()
    if len(cells) < 2 + len(headers):
        return None
    steps_count = int(cells[1])
    values: dict[str, float] = {}
    for h, v in zip(headers, cells[2:2 + len(headers)]):
        try:
            values[h] = float(v)
        except ValueError:
            pass
    values["__steps__"] = steps_count
    values["__speed_factor__"] = speed_factor
    return values


def sweep(counts: list[int], duration_s: int, basic_time_step: int, disable_time: float, disable_threshold: float):
    WORLDS_DIR.mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    quit_steps = max(1, int(duration_s * 1000 / basic_time_step))
    rows = []
    for n in counts:
        world = WORLDS_DIR / f"granular_n{n:04d}.omniworld"
        log = LOGS_DIR / f"granular_n{n:04d}.perf"
        actual_n = write_world(world, n, basic_time_step, disable_time, disable_threshold, quit_steps)
        print(f"[spike] N={n} (actual={actual_n}) -> {world.name}", flush=True)
        exit_code, wall_s = run_headless(world, log, duration_s)
        perf = parse_perf_log(log)
        if perf is None:
            print(f"[spike]   no perf log produced (exit_code={exit_code}, wall={wall_s:.1f}s)", flush=True)
            rows.append({"n": actual_n, "wall_s": round(wall_s, 1), "missing_log": True})
            continue
        rows.append({
            "n": actual_n,
            "wall_s": round(wall_s, 1),
            "steps": perf.get("__steps__", 0),
            "physics_ms": round(perf.get("physics(ms)", 0.0), 3),
            "pre_physics_ms": round(perf.get("prePhysics(ms)", 0.0), 3),
            "post_physics_ms": round(perf.get("postPhysics(ms)", 0.0), 3),
            "loading_ms": round(perf.get("loading(ms)", 0.0), 3),
            "render_ms": round(perf.get("mainRendering(ms)", 0.0), 3),
            "fps": round(perf.get("mainFPS", 0.0), 2),
            "controller_ms": round(perf.get("controller:spike_quit(ms)", 0.0), 3),
            "speed_factor": round(perf.get("__speed_factor__", 0.0), 3),
        })
    return rows


def render_markdown(rows: list[dict], duration_s: int, basic_time_step: int, disable_time: float, disable_threshold: float) -> str:
    lines: list[str] = []
    lines.append("# Granular-Physics Spike Results")
    lines.append("")
    lines.append("Auto-generated by `scripts/dev/granular_spike.py`. Companion data for")
    lines.append("[docs/developer/granular-physics-plan.md](../../docs/developer/granular-physics-plan.md).")
    lines.append("")
    lines.append(f"- duration per run: **{duration_s} s wall time**")
    lines.append(f"- basicTimeStep: **{basic_time_step} ms**")
    lines.append(f"- physicsDisableTime: **{disable_time} s**")
    lines.append(f"- physicsDisableLinearThreshold / AngularThreshold: **{disable_threshold} / {disable_threshold}**")
    lines.append(f"- mode: `--batch --mode=fast --no-rendering --minimize`")
    lines.append("")
    lines.append("Note: `--no-rendering` is set, so `render_ms` and `fps` columns will be 0.")
    lines.append("This isolates the *physics* cost so we can confirm whether physics is")
    lines.append("the active-phase bottleneck the plan attributes it to.")
    lines.append("")
    lines.append("| N spheres | wall s | steps | loading ms | physics ms/step | post-physics ms | sim speed |")
    lines.append("|---|---|---|---|---|---|---|")
    for r in rows:
        if r.get("missing_log"):
            lines.append(f"| {r['n']} | {r.get('wall_s', '?')} | — | — | — | — | (no log) |")
        else:
            lines.append(
                f"| {r['n']} | {r['wall_s']} | {r['steps']} | "
                f"{r.get('loading_ms', 0)} | {r['physics_ms']} | "
                f"{r['post_physics_ms']} | {r['speed_factor']}x |"
            )
    lines.append("")
    lines.append("## Reading this")
    lines.append("")
    lines.append("- **physics ms/step** is the average wall-clock time spent inside ODE per simulated step. With `basicTimeStep=32 ms`, anything under ~32 ms here means the sim can run real-time or faster.")
    lines.append("- **sim/real** is `speedFactor` — sim seconds per real second. < 1 means the sim is *behind* real time. Once the pile settles and bodies auto-disable, this should jump back up.")
    lines.append("- **steps** is the total simulated step count over the wall-clock window. If physics blew past real-time, fewer steps were achieved than `1000 * duration / basicTimeStep`.")
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser(description="Granular physics measurement spike.")
    p.add_argument("--counts", type=int, nargs="+", default=[100, 200, 400, 600])
    p.add_argument("--duration", type=int, default=15, help="seconds of wall time per run")
    p.add_argument("--basic-time-step", type=int, default=32)
    p.add_argument("--disable-time", type=float, default=0.5)
    p.add_argument("--disable-threshold", type=float, default=0.05)
    args = p.parse_args()
    rows = sweep(args.counts, args.duration, args.basic_time_step, args.disable_time, args.disable_threshold)
    md = render_markdown(rows, args.duration, args.basic_time_step, args.disable_time, args.disable_threshold)
    out = SPIKE_DIR / "results.md"
    out.write_text(md, encoding="utf-8")
    print(f"\n[spike] wrote {out.relative_to(REPO_ROOT)}")
    print(md)
    return 0


if __name__ == "__main__":
    sys.exit(main())
