#!/usr/bin/env python
# Copyright 2026 OmniLink
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Phase I of the Webots->OmniSim rebrand — webots/*.h are deprecation shims.

Canonical public C / C++ controller headers live under

    include/controller/c/omnisim/...
    include/controller/cpp/omnisim/...

This script mirrors every one as a one-line forwarder under the legacy
``webots/`` path so external controllers that still write::

    #include <webots/robot.h>
    #include <webots/Robot.hpp>

keep compiling. New code should use ``<omnisim/...>`` directly.

Idempotent: regenerate the entire shim tree on every run.
"""

from __future__ import annotations

import sys
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
LANG_DIRS = (
    ("c", "include/controller/c"),
    ("cpp", "include/controller/cpp"),
)


# These shims REPLACE the upstream Webots headers in place (git tracks them as a
# modification of the original path, not as new files), so Apache-2.0 §4(c) requires
# us to keep Cyberbotics' copyright notice on them and §4(b) requires the
# modification notice. Emit both here, or a regeneration silently strips them and
# tests/sources/test_license.py goes red. See docs/developer/copyright-headers.md.
_MODIFICATION_NOTICE = (
    "Modifications copyright 2026 OmniLink, licensed under the Apache License, Version 2.0."
)

_APACHE2_LICENSE_C = """/*
 * Copyright 1996-2024 Cyberbotics Ltd.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 * %s
 */
""" % _MODIFICATION_NOTICE

_APACHE2_LICENSE_CPP = """// Copyright 1996-2024 Cyberbotics Ltd.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// %s
""" % _MODIFICATION_NOTICE


def _emit_shim(c_or_cpp: str, target: Path, rel: str):
    target.parent.mkdir(parents=True, exist_ok=True)
    licence = _APACHE2_LICENSE_C if c_or_cpp == "c" else _APACHE2_LICENSE_CPP
    note = (
        f"\n"
        f"// Auto-generated by scripts/dev/make_omnisim_header_forwarders.py\n"
        f"// Deprecation shim for the canonical omnisim/ header. New code\n"
        f"// should prefer the omnisim/ path; the webots/ path is kept so\n"
        f"// legacy controllers (e.g. the Cyberbotics device tutorials)\n"
        f"// keep compiling unchanged.\n"
    )
    # Quoted includes relative to the shim itself: resolution then never
    # depends on -I flags, so the shims work from C controller builds,
    # C++ controller builds (whose include path lacks controller/c) and
    # transitive cross-tree hops alike.
    ups = "../" * (rel.count("/") + 1)
    if c_or_cpp == "c":
        guard = f"WEBOTS_DEPR_{rel.upper().replace('/', '_').replace('.', '_')}"
        body = f"#ifndef {guard}\n"
        body += f"#define {guard}\n"
        body += f'#include "{ups}omnisim/{rel}"\n'
        body += f"#endif\n"
    else:
        body = f'#pragma once\n#include "{ups}omnisim/{rel}"\n'
    target.write_text(licence + note + body, encoding="utf-8")


def main() -> int:
    total = 0
    for lang, rel_root in LANG_DIRS:
        root = REPO_ROOT / rel_root
        omnisim_dir = root / "omnisim"
        webots_dir = root / "webots"
        if not omnisim_dir.is_dir():
            print(f"[omnisim-headers] missing {rel_root}/omnisim, skipping {lang}")
            continue
        ext = ".h" if lang == "c" else ".hpp"
        for src in sorted(omnisim_dir.rglob(f"*{ext}")):
            rel = src.relative_to(omnisim_dir).as_posix()
            dst = webots_dir / rel
            _emit_shim(lang, dst, rel)
            total += 1
        print(f"[omnisim-headers] {lang}: wrote {sum(1 for _ in webots_dir.rglob(f'*{ext}'))} shim header(s)")
    print(f"[omnisim-headers] total: {total}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
