# Quad rough-terrain benchmark: run a quadruped's residual RL walk policy on the
# difficult track (<robot>_rough_track.wbt) and report how far it gets / where it
# falls. Terrain = static boxes made collidable with OMNISIM_NEWTON_STATICS=1.
#
# Worlds are generated by projects/policies/research/tools/generate_rough_track.py.
# Bumps: x=6(3cm) 8(5cm) 10(7cm) 12(10cm) 14(14cm) 16(18cm); rubble x18-24.
#
# Usage: scripts/dev/run_quad_rough_track.ps1 -Robot {omniquad,go2,b2} [-Duration 60] [-Bare] [-Gui]
param(
    [ValidateSet('omniquad','go2','b2')][string]$Robot = 'omniquad',
    [int]$Duration = 60,
    [switch]$Bare,            # zero the residual (test the deterministic trot base on terrain)
    [switch]$Gui,
    [string]$Policy = "",     # override ONNX (e.g. a terrain-finetuned policy)
    [double]$ActScale = 0     # override residual scale (0 = default 0.15; match the policy's --res-scale)
)
$root = (Resolve-Path "$PSScriptRoot\..\..").Path
$world = "$root\projects\policies\research\worlds\${Robot}_rough_track.omniworld"
$log   = "$root\_scratch\${Robot}_rough.log"
$pol   = "$root\projects\policies\research\inference\policies"
New-Item -ItemType Directory -Force -Path "$root\_scratch" | Out-Null

# Common Newton env (matches the walk-deploy launchers) + collidable terrain.
$env:OMNISIM_HOME = $root
$env:OMNISIM_LOG_PATH = "$root\_scratch\omnisim_log_${Robot}_rough.txt"
$env:OMNISIM_NEWTON_FORCE_MUJOCO = "1"; $env:OMNISIM_REQUIRE_NEWTON = "1"; $env:OMNISIM_REQUIRE_MUJOCO_SOLVER = "1"
$env:OMNISIM_NEWTON_MJWARP = "1"; $env:OMNISIM_NEWTON_STATICS = "1"
$env:OMNISIM_URDF_USE_INERTIA = "1"; $env:OMNISIM_NEWTON_WRAPPER_USES_OWN_SHAPE = "1"; $env:OMNISIM_NEWTON_SEED_POSE = "1"
$env:OMNISIM_NEWTON_GROUND_MU = "2.0"; $env:OMNISIM_NEWTON_SUBSTEPS = "8"

# Per-robot drive gains + gait + policy (must match each walk-deploy launcher).
switch ($Robot) {
  'omniquad' { $ke=500; $kd=60;  $vx=0.4; $fr=1.4; $sh=0.06; $bh=0.55; $run='gpu_omniquad_walk_main'; $pfx='OMNIQUAD' }
  'go2'  { $ke=250; $kd=6;   $vx=0.4; $fr=1.8; $sh=0.05; $bh=0.30; $run='gpu_go2_walk_main';  $pfx='GO2'  }
  'b2'   { $ke=1400;$kd=35;  $vx=0.5; $fr=1.3; $sh=0.08; $bh=0.50; $run='gpu_b2_walk_main';   $pfx='B2'   }
}
$env:OMNISIM_NEWTON_TARGET_KE = "$ke"; $env:OMNISIM_NEWTON_TARGET_KD = "$kd"
$act = if ($ActScale -gt 0) { $ActScale } else { 0.15 }
Set-Item "Env:${pfx}_GAIT_VX" "$vx"; Set-Item "Env:${pfx}_GAIT_FREQ" "$fr"; Set-Item "Env:${pfx}_GAIT_DUTY" "0.6"
Set-Item "Env:${pfx}_GAIT_STEP_H" "$sh"; Set-Item "Env:${pfx}_GAIT_BODY_H" "$bh"; Set-Item "Env:${pfx}_ACT_SCALE" "$act"
Set-Item "Env:${pfx}_DEPLOY_LOG" $log
if ($Bare)        { Set-Item "Env:${pfx}_POLICY_ONNX" "$root\__no_policy__" }
elseif ($Policy)  { Set-Item "Env:${pfx}_POLICY_ONNX" $Policy }
else              { Set-Item "Env:${pfx}_POLICY_ONNX" "$pol\$run\policy.onnx" }

$guiArg = ""; if ($Gui) { $guiArg = "--gui" }
Write-Host "[$Robot rough-track] STATICS=1 $(if($Bare){'BARE'}else{'RL policy'}) dur=${Duration}s"
python -u "$root\scripts\dev\headless_runner.py" $world --duration $Duration $guiArg 2>&1 | Select-Object -Last 2

Write-Host "----- $Robot result -----"
if (Test-Path $log) {
    $bumps = @(@(6,3),@(8,5),@(10,7),@(12,10),@(14,14),@(16,18))
    $pts = Get-Content $log | Where-Object { $_ -match '^\[t=' } | ForEach-Object {
        if ($_ -match 't=([\d.]+)s.*x=([+\-.\d]+).*y=([+\-.\d]+).*bz=([\d.]+).*roll=([+\-.\d]+).*pitch=([+\-.\d]+)') {
            [pscustomobject]@{ t=[double]$Matches[1]; x=[double]$Matches[2]; y=[double]$Matches[3]; bz=[double]$Matches[4]; roll=[double]$Matches[5]; pitch=[double]$Matches[6] }
        }
    }
    if ($pts) {
        $maxx = ($pts | Measure-Object x -Maximum).Maximum
        $fall = $pts | Where-Object { $_.bz -lt 0.20 -or [math]::Abs($_.roll) -gt 1.0 -or [math]::Abs($_.pitch) -gt 1.0 } | Select-Object -First 1
        $cleared = ($bumps | Where-Object { $maxx -gt ($_[0] + 0.3) } | ForEach-Object { "$($_[1])cm" }) -join ', '
        Write-Host ("  max forward x = {0:N2} m | bumps cleared: {1}" -f $maxx, $(if($cleared){$cleared}else{'NONE'}))
        if ($fall) { Write-Host ("  FELL @ t={0:N0}s x={1:N2} (bz={2:N2} roll={3:N2})" -f $fall.t,$fall.x,$fall.bz,$fall.roll) }
        else { Write-Host "  no collapse detected" }
    } else { Write-Host "  (no [t=] samples)" }
} else { Write-Host "  (no deploy log)" }
